/* Public-information-only scouting. No access to trueTools, potentialTools or growth outcomes. */
(function(root){'use strict';const D=root.DraftData||(typeof require!=='undefined'?require('./data.js'):null);
const STYLES={balanced:'균형형',immediate:'즉전형',floor:'안정형',ceiling:'실링형'};
const needs={SP:[['stamina','긴 이닝을 맡을 선발',45,'선발 이닝 부담을 줄여야 합니다.'],['command','볼넷을 줄일 커맨드형 선발',45,'선발의 경기 운영 안정성이 필요합니다.'],['stuff','헛스윙을 만들 강속구 선발',50,'타자를 압도할 구위가 부족합니다.']],RP:[['stuff','강한 공을 던질 불펜',50,'접전에서 삼진을 만들 자원이 필요합니다.'],['command','스트라이크를 던질 불펜',45,'불펜의 볼넷을 줄이는 것이 과제입니다.'],['breaking','결정구가 있는 불펜',50,'다른 유형의 결정구를 더하고 싶습니다.']],C:[['defense','수비가 안정적인 포수',45,'포수진의 수비 안정성을 보강합니다.'],['ready','바로 백업 경쟁을 할 포수',40,'단기적으로 포수 뎁스가 필요합니다.'],['scoutCeiling','차세대 주전 포수',50,'장기적인 포수 세대교체를 준비합니다.']],IF:[['contact','배트에 공을 맞힐 내야수',45,'내야 타선의 컨택을 보강합니다.'],['power','장타를 보탤 내야수',50,'코너 내야에 장타가 필요합니다.'],['defense','수비가 안정적인 내야수',45,'내야 수비의 안정성을 높입니다.'],['floorGrade','역할이 분명한 내야수',40,'안정적인 백업 경쟁 자원이 필요합니다.']],OF:[['power','공을 멀리 보낼 외야수',50,'외야 타선의 장타 생산을 높입니다.'],['speed','발이 빠른 외야수',50,'주루와 외야 기동력을 보강합니다.'],['defense','넓게 수비할 외야수',50,'외야 수비 범위를 개선합니다.'],['contact','컨택이 좋은 외야수',45,'외야 타선의 연결 능력을 보강합니다.']]};
function plans(seed,teams){return Object.fromEntries(teams.map(t=>{const r=D.rng(seed+'-club06-'+t.id),style=D.pick(Object.keys(STYLES),r),preference=D.pick(['균형','고졸','대졸','해외 경력'],r);const detailedNeeds=t.needs.map(role=>{const [key,label,target,reason]=D.pick(needs[role],r);return {role,key,label,target,reason};});return [t.id,{staff:{style,label:STYLES[style],preference},detailedNeeds}];}));}
function value(p,key){return p.tools?.[key]??p[key]??20;}
function fit(p,t){const n=t.needs.indexOf(p.role);if(n<0)return 25;const base=[100,80,60][n],need=t.detailedNeeds?.find(x=>x.role===p.role);return need?Math.round(base*(.74+.26*D.clamp(value(p,need.key)/need.target,.4,1))):base;}
function score(p,t,style=t.staff?.style||'balanced'){
 const base=style==='immediate'?p.ready*.70+p.scoutCeiling*.30:style==='floor'?p.floorGrade*.50+p.ready*.25+p.scoutCeiling*.25:style==='ceiling'?p.ceilingGrade*.45+p.scoutCeiling*.45+p.ready*.10:p.ready*.4+p.scoutCeiling*.6;
 const pref=t.staff?.preference,bonus=(pref===p.pathway||pref==='해외 경력'&&(p.entryCategory==='overseas-return'||p.pathway==='해외파'))?1.2:0;
 return base+fit(p,t)*.065+bonus;
}
function explanation(p,t){const need=t.detailedNeeds?.find(x=>x.role===p.role);return [`현재 ${p.ready} / 미래 가치 ${p.scoutCeiling} · ${p.pickTags.join(' + ')}.`,need?`${need.label}: ${D.grades.LABELS[need.key]||{ready:'현재 기량',scoutCeiling:'미래 가치',floorGrade:'플로어'}[need.key]} ${value(p,need.key)} (관찰 목표 ${need.target}). ${need.reason}`:'우선 보강 포지션보다 선수의 개별 가치를 보는 선택입니다.',`낮은 쪽 전망 ${p.floorGrade} / 잘 풀릴 때 ${p.ceilingGrade}. 관측 불확실성 ${p.uncertainty}; 어느 결과도 보장하지 않습니다.`];}
function recommend(players,t,local){const eligible=players.filter(p=>!local||p.regionalEligible&&p.region===t.region),chosen=[];for(const style of [t.staff.style,'immediate','ceiling','floor','balanced']){const p=eligible.filter(p=>!chosen.some(x=>x.playerId===p.id)).map(p=>({p,score:score(p,t,style)})).sort((a,b)=>b.score-a.score||a.p.rank-b.p.rank)[0]?.p;if(p)chosen.push({playerId:p.id,angle:STYLES[style],lines:explanation(p,t)});if(chosen.length===3)break;}return {staff:t.staff,scope:local?'지역 1차':'전국 1라운드',candidates:chosen};}
const api={STYLES,plans,value,fit,score,explanation,recommend};root.DraftScouting=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
