const {chromium}=require('playwright-core'),{execSync}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_BIN||execSync('command -v chromium').toString().trim(),headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const out=path.join(__dirname,'screenshots');fs.mkdirSync(out,{recursive:true});let checks=0;
 async function layout(page,label){const size=await page.evaluate(()=>({view:innerWidth,doc:document.documentElement.scrollWidth,body:document.body.scrollWidth}));assert(size.doc<=size.view+1&&size.body<=size.view+1,label+JSON.stringify(size));checks++;}
 for(const width of [390,768,1280])for(const difficulty of ['easy','normal','hard']){
  const context=await browser.newContext({viewport:{width,height:1000},deviceScaleFactor:1,acceptDownloads:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const local=difficulty!=='normal';
  await page.goto('file://'+path.join(__dirname,'../index.html'));assert((await page.title()).includes('v0.4'));await layout(page,'setup');assert.equal(await page.locator('#local-toggle').isChecked(),false);
  await page.locator(`[data-action="difficulty"][data-id="${difficulty}"]`).click();if(local)await page.locator('#local-toggle').check();await page.locator('[data-action="team"][data-id="lg"]').click();await page.locator('[data-action="start"]').click();await layout(page,'mock');assert.equal(await page.locator('.mock-list li').count(),local?40:20);
  if(difficulty==='normal')await page.screenshot({path:path.join(out,`mock-${width}.png`),fullPage:true});
  const oldForecasts=await page.evaluate(()=>JSON.parse(localStorage.getItem('draft-room-kbo-v4-spotlight')).game.forecasts);await page.reload();assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('draft-room-kbo-v4-spotlight')).game.forecasts),oldForecasts);
  await page.locator('[data-action="begin-draft"]').click();await layout(page,'draft');await page.locator('#sort').selectOption('hr');await page.locator('[data-action="sort-direction"]').click();await page.locator('#sort').selectOption('outs');await page.locator('.history summary').click();await layout(page,'history');
  await page.locator('[data-action="pick"]').click();await page.locator('[data-action="confirm-pick"]').click();assert(await page.locator('.news-article').isVisible());assert.equal(await page.locator('.comment').count(),3);await layout(page,'live news');if(difficulty==='normal')await page.screenshot({path:path.join(out,`news-${width}.png`)});await page.keyboard.press('Escape');await page.reload();
  let guard=0;while(await page.locator('[data-action="pick"]').count()){await page.locator('[data-action="pick"]').click();await page.locator('[data-action="confirm-pick"]').click();if(await page.locator('.modal').count())await page.keyboard.press('Escape');assert(++guard<7);}
  await layout(page,'gm');assert(await page.locator('[data-action="simulate"]').isDisabled());if(difficulty==='normal')await page.screenshot({path:path.join(out,`gm-${width}.png`),fullPage:true});
  await page.locator(`[data-action="gm-choice"][data-id="${{easy:'immediate',normal:'development',hard:'needs'}[difficulty]}"]`).click();const fans=await page.locator('.fan-pill').textContent();await page.reload();assert.equal(await page.locator('.fan-pill').textContent(),fans);assert.equal(await page.locator('[data-action="gm-choice"]').count(),0);
  await page.locator('[data-action="simulate"]').click();await layout(page,'season');assert.equal(await page.locator('.season-card').count(),local?6:5);await page.locator('[data-action="owner"]').click();await layout(page,'owner');assert(await page.locator('.pledge-review').isVisible());
  await page.locator('[data-action="fan-history"]').click();await layout(page,'fan ledger');assert.equal(await page.locator('.fan-timeline li').count(),local?5:4);await page.keyboard.press('Escape');await page.locator('[data-action="mock-archive"]').click();await layout(page,'mock archive');assert(await page.locator('.forecast-result').count()>0);await page.keyboard.press('Escape');await page.locator('[data-action="news-room"]').click();await layout(page,'news archive');assert.equal(await page.locator('.news-article').count(),local?20:10);await page.keyboard.press('Escape');
  if(difficulty==='normal')await page.screenshot({path:path.join(out,`owner-${width}.png`),fullPage:true});const pending=page.waitForEvent('download');await page.locator('[data-action="download"]').click();const download=await pending;assert(download.suggestedFilename().startsWith('draft-room-v04-'));if(difficulty==='normal')await download.saveAs(path.join(out,`result-${width}.png`));
  assert.equal(errors.length,0,errors.join('\n'));console.log(`PASS ${width}px ${difficulty}: preview/reload → draft/news → GM/reload → season → owner/fans/archive → PNG`);await context.close();
 }
 await browser.close();console.log(`PASS ${checks} layout checks; no document overflow; no browser JS errors.`);
})().catch(e=>{console.error(e);process.exit(1);});
