const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM,VirtualConsole}=require('jsdom'),html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),KEY='draft-room-kbo-v4-spotlight';
function open(saved=null,width=1200,blocked=false){
 const errors=[];let downloads=0;const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));vc.on('error',e=>errors.push(e));
 const dom=new JSDOM(html,{url:'https://draft-room.test',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.innerWidth=width;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.Date.now=()=>123456;w.Math.random=()=>.25;w.HTMLCanvasElement.prototype.getContext=()=>({fillRect(){},fillText(){}});w.HTMLCanvasElement.prototype.toDataURL=()=> 'data:image/png;base64,dGVzdA==';w.HTMLAnchorElement.prototype.click=function(){downloads++;assert(this.download.startsWith('draft-room-v04-'));};if(saved)w.localStorage.setItem(KEY,saved);if(blocked)Object.defineProperty(w,'localStorage',{get(){throw Error('blocked');}});}});
 const w=dom.window,d=w.document,q=s=>d.querySelector(s);return {w,d,q,click(s){const el=q(s);assert(el,'missing '+s);assert(!el.disabled,'disabled '+s);el.click();},change(s,v){const el=q(s);el.value=v;el.dispatchEvent(new w.Event('change',{bubbles:true}));},input(s,v){const el=q(s);el.value=v;el.dispatchEvent(new w.Event('input',{bubbles:true}));},save:()=>w.localStorage.getItem(KEY),close(){assert.equal(errors.length,0,errors.map(e=>e.stack).join('\n'));w.close();},get downloads(){return downloads;}};
}
function begin(ui,team='kiwoom',local=false,difficulty='normal'){
 ui.click(`[data-action="team"][data-id="${team}"]`);if(local)ui.click('#local-toggle');ui.click(`[data-action="difficulty"][data-id="${difficulty}"]`);ui.click('[data-action="start"]');assert(ui.q('.mock-grid'));assert.equal(ui.q('[data-action="pick"]'),null);ui.click('[data-action="begin-draft"]');
}
function draft(ui){let n=0;while(ui.q('[data-action="pick"]')){ui.click('[data-action="pick"]');ui.click('[data-action="confirm-pick"]');if(ui.q('.modal')){assert(ui.q('.news-article'));assert.equal(ui.d.querySelectorAll('.comment').length,3);ui.click('.modal [data-action="close-modal"]');}assert(++n<=6);}assert(ui.q('.gm-section'));assert(ui.q('[data-action="simulate"]').disabled);return n;}
test('setup default, preview autosave, same forecasts on reload and no premature AI pick',()=>{
 let ui=open();assert.equal(ui.q('#local-toggle').checked,false);assert.equal(ui.q('[data-action="difficulty"][aria-pressed="true"]').dataset.id,'normal');ui.click('[data-action="start"]');const saved=ui.save(),forecast=JSON.parse(saved).game.forecasts;assert.equal(JSON.parse(saved).game.picks.length,0);ui.close();ui=open(saved);assert(ui.q('.mock-grid'));assert.deepEqual(JSON.parse(ui.save()).game.forecasts,forecast);ui.click('[data-action="begin-draft"]');assert(ui.q('#profile'));ui.close();
});
test('every club × regional OFF/ON completes normal UI, interviews, fan history, season, owner and PNG',()=>{
 for(const id of ['kiwoom','nc','hanwha','lotte','ssg','kt','doosan','lg','samsung','kia'])for(const local of [false,true]){
  const ui=open(null,local?390:1200);begin(ui,id,local);const count=draft(ui);assert.equal(count,local?6:5);assert.equal(ui.d.querySelectorAll('.quote-card').length,count);ui.click('[data-action="gm-choice"][data-id="development"]');assert(ui.q('.gm-answered'));const after=ui.save();ui.click('[data-action="fan-history"]');assert(ui.q('.fan-timeline'));ui.click('.modal [data-action="close-modal"]');assert.equal(ui.save(),after);ui.click('[data-action="simulate"]');assert.equal(ui.d.querySelectorAll('.season-card').length,count);const season=JSON.parse(ui.save()).game.season;ui.click('[data-action="owner"]');assert(ui.q('.pledge-review'));assert(/^[ABCD]$/.test(ui.q('.grade-letter').textContent));ui.click('[data-action="download"]');assert.equal(ui.downloads,1);ui.click('[data-action="season"]');ui.click('[data-action="interviews"]');assert(!ui.q('[data-action="gm-choice"]'));ui.click('[data-action="simulate"]');assert.deepEqual(JSON.parse(ui.save()).game.season,season);ui.close();
 }
});
test('easy/hard settings persist; completed and partial saves retain the exact newsroom, pledge and fan score',()=>{
 for(const difficulty of ['easy','hard']){let ui=open();begin(ui,'lotte',true,difficulty);ui.click('[data-action="pick"]');ui.click('[data-action="confirm-pick"]');const partial=ui.save();ui.close();ui=open(partial);assert.equal(JSON.parse(ui.save()).game.difficulty,difficulty);assert(ui.q('[data-action="pick"]'));draft(ui);ui.click('[data-action="gm-choice"][data-id="immediate"]');ui.click('[data-action="simulate"]');ui.click('[data-action="owner"]');const complete=ui.save(),fans=ui.q('.fan-pill').textContent;ui.close();ui=open(complete);assert(ui.q('.pledge-review'));assert.equal(ui.q('.fan-pill').textContent,fans);assert.deepEqual(JSON.parse(ui.save()).game,JSON.parse(complete).game);ui.close();}
});
test('all sort controls display matching values, directions, nulls and coexist with search/role/path/tier/star filters',()=>{
 const ui=open();begin(ui);const C=ui.w.DraftCore;assert.equal(ui.q('#sort').options.length,22);
 for(const key of Object.keys(C.rules.SORTS)){ui.change('#sort',key);for(let n=0;n<2;n++){const rows=[...ui.d.querySelectorAll('.player-row')],game=JSON.parse(ui.save()).game,dir=ui.q('[data-action="sort-direction"]').textContent.includes('오름')?'asc':'desc';const expected=C.rules.sortPlayers(C.available(game),key,dir,C.teamById.kiwoom).map(p=>p.id);assert.deepEqual(rows.map(r=>r.dataset.id),Array.from(expected));for(const row of rows.slice(0,3)){const stat=ui.w.DraftView04.sortedStat(C.playerById[row.dataset.id],key,C.teamById.kiwoom);assert.equal(row.querySelector('.p-stat').textContent,stat.value);}ui.click('[data-action="sort-direction"]');}}
 ui.input('#search','없는선수');assert.equal(ui.d.querySelectorAll('.player-row').length,0);ui.click('[data-action="clear-filters"]');ui.change('#pathway','대졸');assert([...ui.d.querySelectorAll('.player-row')].every(r=>C.playerById[r.dataset.id].pathway==='대졸'));ui.change('#pathway','ALL');ui.change('#tier','약소');assert([...ui.d.querySelectorAll('.player-row')].every(r=>C.playerById[r.dataset.id].schoolTier==='약소'));ui.change('#tier','ALL');ui.click('[data-action="role"][data-id="SP"]');assert([...ui.d.querySelectorAll('.player-row')].every(r=>C.playerById[r.dataset.id].role==='SP'));ui.click('.player-row');ui.click('[data-action="star"]');ui.click('[data-action="only-stars"]');assert.equal(ui.d.querySelectorAll('.player-row').length,1);ui.close();
});
test('newsroom and mock archive can reopen without fan changes; modal keyboard can reach forecast summaries',()=>{
 const ui=open();begin(ui,'lg',true);ui.click('[data-action="mock-archive"]');const buttons=[...ui.d.querySelectorAll('.modal button,.modal summary')];buttons.at(-1).focus();ui.d.dispatchEvent(new ui.w.KeyboardEvent('keydown',{key:'Tab',bubbles:true}));assert.equal(ui.d.activeElement,buttons[0]);ui.d.dispatchEvent(new ui.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert(!ui.q('.modal'));
 const before=ui.save();ui.click('[data-action="news-room"]');assert(ui.d.querySelectorAll('.news-article').length>0);assert(ui.q('.community'));ui.click('.modal [data-action="close-modal"]');assert.equal(ui.save(),before);ui.click('[data-action="catalog"]');assert.equal(ui.d.querySelectorAll('.catalog-list li').length,132);assert(ui.q('.catalog-list').textContent.includes('미국 롱아일랜드하버대'));ui.click('.modal [data-action="close-modal"]');ui.close();
});
test('blocked storage, malformed save and old version fail gracefully without changing previous storage',()=>{
 const blocked=open(null,390,true);assert(blocked.q('#storage-status').textContent.includes('제한'));begin(blocked);draft(blocked);blocked.click('[data-action="gm-choice"][data-id="needs"]');blocked.click('[data-action="simulate"]');blocked.close();
 for(const saved of ['{bad',JSON.stringify({selectedTeam:'constructor',difficulty:'__proto__',game:{version:3}})]){const ui=open(saved);assert.equal(ui.d.querySelectorAll('.team-card').length,10);assert.equal(ui.q('[data-action="difficulty"][aria-pressed="true"]').dataset.id,'normal');ui.close();}
});
