const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM,VirtualConsole}=require('jsdom');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),KEY='draft-room-kbo-v5-five-years';
function boot(saved){const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));vc.on('error',e=>errors.push(String(e)));const dom=new JSDOM(html,{runScripts:'dangerously',url:'https://draft.test/',virtualConsole:vc,beforeParse(w){w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.Date.now=()=>2000000000000;w.Math.random=()=>.42;if(saved)w.localStorage.setItem(KEY,JSON.stringify(saved));}});return {dom,w:dom.window,doc:dom.window.document,errors};}
function click(env,sel){const el=env.doc.querySelector(sel);assert(el,'missing '+sel);assert(!el.disabled,'disabled '+sel);el.click();}
function saved(env){return JSON.parse(env.w.localStorage.getItem(KEY));}
function draft(env,local=false){if(local){const input=env.doc.querySelector('#local-toggle');input.checked=true;input.dispatchEvent(new env.w.Event('change',{bubbles:true}));}click(env,'[data-action=start]');click(env,'[data-action=begin-draft]');while(saved(env).game.phase==='draft'){click(env,'[data-action=pick]');click(env,'[data-action=confirm-pick]');if(env.doc.querySelector('[role=dialog]'))click(env,'[data-action=close-modal]');}click(env,'[data-action=gm-choice][data-id=development]');click(env,'[data-action=simulate]');}
test('offline UI: draft, early filter, both 7/8-pick flows, records, profiles, all five years, review',()=>{
 for(const local of [false,true]){const a=boot();try{
  assert.match(a.doc.querySelector('.version').textContent,/0.5/);click(a,'[data-action=rules]');assert.match(a.doc.querySelector('[role=dialog]').textContent,/고졸 144/);click(a,'[data-action=close-modal]');draft(a,local);assert.equal(saved(a).game.picks.length,local?80:70);assert.match(a.doc.querySelector('h1').textContent,/첫 번째 시즌/);assert.equal(a.doc.querySelectorAll('[data-action=view-year]').length,1);
  click(a,'[data-action=records]');assert.equal(a.doc.querySelectorAll('.record-table tbody tr').length,local?80:70);click(a,'.record-table [data-action=career-player]');assert.match(a.doc.querySelector('[role=dialog]').textContent,/누적 성적/);assert(!a.doc.querySelector('[role=dialog]').textContent.includes('endState'));click(a,'[data-action=close-modal]');
  const scope=a.doc.querySelector('#record-scope');scope.value='current';scope.dispatchEvent(new a.w.Event('change',{bubbles:true}));click(a,'[data-action=records-close]');
  let clock=2000000001000;a.w.Date.now=()=>clock;
  for(let i=1;i<5;i++){click(a,'[data-action=next-season]');clock+=1000;assert.equal(saved(a).game.career.years.length,i+1);}
  const before=JSON.stringify(saved(a).game.career);click(a,'[data-action=view-year][data-index="0"]');assert.match(a.doc.querySelector('.career-hero').textContent,/2027/);assert.equal(JSON.stringify(saved(a).game.career),before);click(a,'[data-action=owner]');assert.match(a.doc.querySelector('h1').textContent,/다섯 시즌/);assert.equal(a.doc.querySelectorAll('.record-table tbody tr').length,10);assert(!a.doc.querySelector('[data-action=next-season]'));assert(a.w.DraftCore.validate(saved(a).game));assert.deepEqual(a.errors,[]);
  const b=boot(saved(a));assert.match(b.doc.querySelector('h1').textContent,/다섯 시즌/);assert.deepEqual(b.errors,[]);b.dom.window.close();
 }finally{a.dom.window.close();}}
});
test('record room works during draft and preserves draft state and filters on return',()=>{
 const a=boot();try{click(a,'[data-action=start]');click(a,'[data-action=begin-draft]');const path=a.doc.querySelector('#pathway');assert([...path.options].some(x=>x.value==='대학 얼리'));path.value='대학 얼리';path.dispatchEvent(new a.w.Event('change',{bubbles:true}));const before=JSON.stringify(saved(a).game);click(a,'[data-action=records]');assert.match(a.doc.querySelector('#main').textContent,/아직 시즌/);click(a,'[data-action=records-close]');assert.equal(JSON.stringify(saved(a).game),before);assert.equal(a.doc.querySelector('#pathway').value,'대학 얼리');assert.deepEqual(a.errors,[]);}finally{a.dom.window.close();}
});
test('double next-season clicks within 900ms do not skip a year; news/fans and interview archive remain usable',()=>{
 const a=boot();try{draft(a);a.w.Date.now=()=>2000000002000;click(a,'[data-action=next-season]');click(a,'[data-action=next-season]');assert.equal(saved(a).game.career.years.length,2);for(const action of ['mock-archive','news-room','fan-history']){click(a,`[data-action=${action}]`);assert(a.doc.querySelector('[role=dialog]'));click(a,'[data-action=close-modal]');}click(a,'[data-action=interviews]');assert.match(a.doc.querySelector('[data-action=simulate]').textContent,/돌아가기/);click(a,'[data-action=simulate]');assert.equal(saved(a).game.career.years.length,2);assert.deepEqual(a.errors,[]);}finally{a.dom.window.close();}
});
