/* Real Chromium UI + offline file smoke. CHROMIUM_BIN may override the executable. */
const {chromium}=require('playwright-core'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const base=path.resolve(__dirname,'..'),out=path.join(__dirname,'screenshots-v06'),KEY='draft-room-kbo-v6-scouting';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_BIN||'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const reports=[];
try{
 for(const cfg of [{name:'desktop-normal-on',width:1440,height:1000,difficulty:'normal',local:true,team:'lg'},{name:'mobile-hard-off',width:390,height:844,difficulty:'hard',local:false,team:'kiwoom'},{name:'tablet-easy-on',width:820,height:1180,difficulty:'easy',local:true,team:'samsung'},{name:'smallphone-normal-off',width:320,height:740,difficulty:'normal',local:false,team:'kia'}]){
  const ctx=await browser.newContext({viewport:{width:cfg.width,height:cfg.height},acceptDownloads:true});const page=await ctx.newPage(),errors=[];page.on('pageerror',err=>errors.push(err.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  await page.goto(pathToFileURL(path.join(base,'index.html')).href);await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(out,cfg.name+'-setup.png')});
  const overflow=async()=>page.evaluate(()=>({body:document.documentElement.scrollWidth,viewport:innerWidth}));const setupSize=await overflow();assert(setupSize.body<=setupSize.viewport+1,JSON.stringify({cfg:cfg.name,setupSize}));if(cfg.width<=600)assert(await page.locator('#steps').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'all six mobile steps fit');
  await page.locator(`[data-action=team][data-id=${cfg.team}]`).click();await page.locator(`[data-action=difficulty][data-id=${cfg.difficulty}]`).click();if(cfg.local)await page.locator('#local-toggle').check();await page.locator('[data-action=start]').click();await page.locator('[data-action=scout-briefing]').click();assert.equal(await page.locator('.recommendation').count(),3);assert.equal(await page.locator('.scouting-club li').count(),3);await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(250);await page.screenshot({path:path.join(out,cfg.name+'-recommend.png'),fullPage:true});await page.reload();assert.equal(await page.locator('.recommendation').count(),3);await page.locator('[data-action=begin-draft]').click();assert.equal(await page.locator('.tool-grade-table tbody tr').count(),4);assert.equal(await page.locator('.favorite-note').count(),cfg.difficulty==='easy'?1:0);await page.locator('[data-action=pick-type][data-id=실링]').click();await page.locator('[data-action=pick-type][data-id=ALL]').click();
  const capture=async name=>{await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(200);await page.screenshot({path:path.join(out,cfg.name+'-'+name+'.png')});};
  const get=()=>page.evaluate(key=>{const stored=JSON.parse(localStorage.getItem(key));if(JSON.stringify(stored.save).length>2000)throw Error('autosave is not compact');return {...stored,game:stored.save&&DraftCore.loadSave(stored.save).game};},KEY);let game=(await get()).game;
  while(game.phase==='draft'){
   if(game.picks.filter(s=>s.teamId===game.teamId).length===0){await capture('draft');const body=await page.locator('#main').innerText();assert(!/undefined|NaN|100점 척도/.test(body));}
   await page.locator('[data-action=pick]').click();await page.locator('[data-action=confirm-pick]').click();if(await page.locator('[role=dialog]').count())await page.locator('[data-action=close-modal]').first().click();game=(await get()).game;
  }
  assert.equal(game.picks.length,cfg.local?120:110);assert.equal(game.phase,'negotiation');await capture('negotiation');await page.locator('[data-action=offer-confirm]').click();if(await page.locator('[data-action=counter-confirm]').count()){await page.locator('[data-action=counter-toggle]').first().click();await page.locator('[data-action=counter-confirm]').click();}game=(await get()).game;assert.equal(game.phase,'signing');let devPicked=0;for(let k=0;k<2;k++){const t=page.locator('[data-action=dev-toggle]:not([aria-pressed=true]):not([disabled])');if(!(await t.count()))break;await t.first().click();devPicked++;}await page.locator('[data-action=dev-confirm]').click();game=(await get()).game;assert.equal(game.devSigns.filter(s=>s.teamId===game.teamId).length,devPicked);assert(game.devSigns.length>=32);for(const q of await page.locator('[data-action=gm-answer]').evaluateAll(bs=>[...new Set(bs.map(b=>b.dataset.q))]))await page.locator(`[data-action=gm-answer][data-q=${q}]${q==='pledge'?'[data-id=development]':''}`).first().click();await capture('press');await page.locator('[data-action=gm-confirm]').click();await page.locator('[data-action=simulate]').click();await capture('season');{const gg=(await get()).game,own=gg.picks.filter(x=>x.teamId===gg.teamId&&!x.refused).length+gg.devSigns.filter(x=>x.teamId===gg.teamId).length;assert.equal(await page.locator('.development-grid article').count(),own);}
  await page.locator('[data-action=records]').first().click();await page.locator('#record-team').selectOption('ALL');assert.equal(await page.locator('.record-table tbody tr:not(.second)').count(),game.picks.filter(s=>!s.refused).length+game.devSigns.length);await page.locator('#record-level').selectOption('futures');await page.locator('#record-sort').selectOption('wins');await page.locator('#record-sort').selectOption('era');await page.locator('.record-table [data-action=career-player]').first().click();assert.equal(await page.locator('.tool-grade-table tbody tr').count(),4);assert(await page.locator('.tool-snapshot').count()>=2);assert(!/undefined|NaN|\/ 100\./.test(await page.locator('.career-profile').innerText()));await page.screenshot({path:path.join(out,cfg.name+'-profile.png')});await page.keyboard.press('Escape');assert.equal(await page.locator('[role=dialog]').count(),0);
  const roomSize=await overflow();assert(roomSize.body<=roomSize.viewport+1,JSON.stringify({cfg:cfg.name,roomSize}));await capture('records');if(cfg.width<700){const scroller=page.locator('.table-scroll').first();await scroller.focus();await page.keyboard.press('ArrowRight');await page.waitForTimeout(250);assert(await scroller.evaluate(el=>el.scrollLeft>0),'mobile table keyboard scroll');}await page.locator('[data-action=records-close]').click();
  const SEASONS=await page.evaluate(()=>DraftCore.Career.SEASONS);let ordered=0;for(let i=1;i<SEASONS;i++){await page.waitForTimeout(950);const svc=page.locator('select[data-service]');if(!ordered&&await svc.count()){await svc.first().selectOption('army');ordered=1;}await page.locator('[data-action=next-season]').click();assert.equal((await get()).game.career.years.length,i+1);await page.reload();assert.equal((await get()).game.career.years.length,i+1);}
  await page.locator('[data-action=owner]').first().click();assert.equal(await page.locator('.record-table tbody tr').count(),10);assert.equal(await page.locator('[data-action=next-season]').count(),0);await capture('review');
  const finalSize=await overflow();assert(finalSize.body<=finalSize.viewport+1,JSON.stringify({cfg:cfg.name,finalSize}));const final=(await get()).game;assert(await page.evaluate(key=>{const s=JSON.parse(localStorage.getItem(key)).save;return s.sim===DraftCore.SIM_VERSION&&s.seasons===DraftCore.Career.SEASONS&&!!DraftCore.loadSave(s).game;},KEY));
  const downloadPromise=page.waitForEvent('download');await page.locator('[data-action=export-save]').first().click();const download=await downloadPromise,saveFile=path.join(__dirname,cfg.name+'-save.json');await download.saveAs(saveFile);assert(fs.statSync(saveFile).size<5000,'exported save is compact');
  await page.locator('[data-action=reset]').click();await page.locator('[data-action=confirm-reset]').click();await page.locator('#import-file').setInputFiles(saveFile);await page.locator('[data-action=confirm-import]').click();assert.deepEqual((await get()).game,final);
  const imagePromise=page.waitForEvent('download');await page.locator('[data-action=download]').click();const image=await imagePromise;await image.saveAs(path.join(out,cfg.name+'-first-year.png'));
  assert.deepEqual(errors,[]);reports.push({case:cfg.name,offline:true,picks:final.picks.length,seasons:final.career.years.length,exportImport:true,firstYearImage:true,scoutingBriefing:true,toolGrades:true,developmentReports:true,horizontalOverflow:false,errors});await ctx.close();
 }
 fs.writeFileSync(path.join(__dirname,'v06-browser-results.json'),JSON.stringify(reports,null,2)+'\n');console.log(JSON.stringify(reports,null,2));console.log('PASS real Chromium offline smoke');
}finally{await browser.close();}})().catch(err=>{console.error(err);process.exit(1);});
