const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/core/engine.js'),D=require('../src/core/prospects.js'),M=require('../src/core/season.js'),S=require('../src/core/scouting.js');
const clone=x=>JSON.parse(JSON.stringify(x));
function draft(seed='unit06',team='lg',local=true,difficulty='normal'){const g=C.createGame(team,local,seed,difficulty);C.openScouting(g);C.beginDraft(g);while(g.phase==='draft')C.addPick(g,C.aiChoice(g).id);C.chooseGM(g,'development');return g;}
function finish(g){C.runSeason(g);while(g.career.years.length<5)C.nextSeason(g);return g;}
function checkStats(s){assert(s.games>=0);if(s.kind==='pitcher'){assert(s.k<=s.outs);assert(s.qs<=s.gs&&s.gs<=s.games);assert(s.wins+s.holds+s.saves<=s.games);assert.equal(s.era,s.outs?D.round(s.er*27/s.outs,2):null);}else{assert(s.hr+s.doubles+s.triples<=s.hits&&s.hits<=s.ab);assert(s.k<=s.ab-s.hits);assert.equal(s.pa,s.ab+s.bb);assert.equal(s.avg,s.ab?D.round(s.hits/s.ab,3):null);assert.equal(s.ops,s.ab?D.round((s.hits+s.bb)/s.pa+(s.hits+s.doubles+2*s.triples+3*s.hr)/s.ab,3):null);}}
test('V6 namespace, strict phase order, 70/80 schedule',()=>{const g=C.createGame('lg',true,'phase');assert.equal(C.VERSION,6);assert.equal(g.schedule.length,80);assert.equal(C.makeSchedule(false).length,70);assert.throws(()=>C.beginDraft(g));assert(C.validate(g));C.openScouting(g);assert(C.validate(g));C.beginDraft(g);assert(C.validate(g));assert.throws(()=>C.openScouting(g));});
test('200 candidates: quota supply, 136 high-school and 8 overseas returnees',()=>{for(let i=0;i<20;i++){const p=D.generatePool('pool06-'+i).players;assert.equal(p.length,200);assert.equal(p.filter(p=>p.quotaEligible).length,30);assert.equal(p.filter(p=>p.pathway==='고졸').length,136);assert.equal(p.filter(p=>p.entryCategory==='overseas-return').length,8);assert.equal(p.filter(p=>p.pathway==='대학 얼리').length,16);assert(p.filter(p=>p.pathway==='MLB 경험 복귀').length<=1);for(const region of D.REGIONS)assert.equal(p.filter(p=>p.pathway==='고졸'&&p.region===region).length,17);}});
test('all public ability grades use 20–80 by fives; FV differs from ceiling',()=>{const p=D.generatePool('grades06').players;for(const x of p){for(const n of [x.ready,x.scoutCeiling,x.floorGrade,x.ceilingGrade,...Object.values(x.tools),...Object.values(x.futureTools)])assert(Number.isInteger(n)&&n>=20&&n<=80&&n%5===0);assert(x.floorGrade<=x.scoutCeiling&&x.scoutCeiling<=x.ceilingGrade);for(const k of Object.keys(x.trueTools))assert(x.trueTools[k]<=x.potentialTools[k]);}assert(p.some(x=>x.ceilingGrade>x.scoutCeiling));assert(p.filter(x=>x.scoutCeiling>=60).length<15);assert(p.some(x=>x.pickTags.length>1));});
test('domestic/overseas biographies and catalog preserve chronology and eligibility',()=>{assert.equal(C.catalog.length,160);assert.equal(new Set(C.catalog.map(x=>x.id)).size,160);for(let i=0;i<10;i++)for(const p of D.generatePool('bio06-'+i).players){assert.equal(D.bio.ageAt(p.birthday),p.age);for(let n=0;n<p.history.length;n++){const h=p.history[n];assert(!h.end||h.start<h.end);if(n)assert(p.history[n-1].end<=h.start);}if(p.proExperience){assert.equal(p.proExperience.domesticPro,false);assert(!p.quotaEligible&&!p.regionalEligible);assert(p.history.at(-1).end<C.DRAFT_DATE);assert.equal(p.proExperience.level,p.currentInstitution.level);}if(p.pathway==='대학 얼리'){assert.equal(p.collegeYear,2);assert(!p.quotaEligible);}}});
test('AI, media and recommendations cannot read hidden talent or preferences',()=>{const g=C.createGame('lg',true,'public06');const forbidden=new Set(['trueTools','potentialTools','trueReady','upside','growthCurve','developmentRate','observerBias','favoriteTeam','lateDevelopment']);const safe=C.poolFor(g).players.map(p=>C.rules.project(new Proxy(p,{get(target,key){if(forbidden.has(key))throw Error('Hidden read: '+key);return target[key];}})));const t=C.teamFor(g);assert.equal(S.recommend(safe,t,true).candidates.length,3);assert(C.rules.aiScores(safe,t,[],'hard','audit').length);assert(C.press.forecast(safe,C.TEAMS.map(t=>C.teamFor(g,t.id)),true,'audit').length);for(const p of safe)for(const key of forbidden)assert(!Object.hasOwn(p,key));});
test('club plans vary by seed, reproduce exactly and respect positions',()=>{const a=S.plans('clubA',C.TEAMS),b=S.plans('clubB',C.TEAMS);assert.deepEqual(a,S.plans('clubA',C.TEAMS));assert.notDeepEqual(a,b);for(const t of C.TEAMS){assert.deepEqual(a[t.id].detailedNeeds.map(n=>n.role),t.needs);assert(S.STYLES[a[t.id].staff.style]);}});
test('same seed and player talent are independent of difficulty and chosen club',()=>{const a=C.createGame('lg',false,'equal06','easy'),pa=clone(C.poolFor(a).players),b=C.createGame('kia',true,'equal06','hard');assert.deepEqual(C.poolFor(b).players,pa);assert.deepEqual(a.clubPlans,b.clubPlans);const p=pa[0],s={round:1,label:'1R',teamId:'lg'};assert.deepEqual(C.simulatePlayer(p,s,a),C.simulatePlayer(p,s,{...a,difficulty:'hard'}));});
test('quota last-pick and global-supply safeguards survive adversarial selection',()=>{for(const local of [true,false]){const g=C.createGame('lg',local,'adversarial06');C.openScouting(g);C.beginDraft(g);while(g.phase==='draft'){const slot=g.schedule[g.cursor],list=C.available(g);assert(list.length);const q=C.quotaStatus(g,slot.teamId);if(slot.round>0&&q.missing&&q.remaining===1)assert(list.every(p=>p.quotaEligible));const p=slot.teamId==='lg'?(list.find(p=>!p.quotaEligible)||list[0]):(list.find(p=>p.quotaEligible)||list[0]);C.addPick(g,p.id);}for(const t of C.TEAMS)assert(C.quotaStatus(g,t.id).count>=1);}});
test('regional and recommendation candidates are eligible, unique, and immutable',()=>{const g=C.createGame('lg',true,'local06'),original=clone(g.scoutReport),forecast=clone(g.forecasts);for(const r of g.scoutReport.candidates)assert(C.eligible(C.getPlayer(g,r.playerId),C.teamFor(g)));C.openScouting(g);C.beginDraft(g);while(g.phase==='draft'){const p=C.aiChoice(g),slot=g.schedule[g.cursor];if(slot.round===0)assert(C.eligible(p,C.teamFor(g,slot.teamId)));C.addPick(g,p.id);}assert.deepEqual(g.scoutReport,original);assert.deepEqual(g.forecasts,forecast);});
test('all 60 club × local × difficulty combinations finish and replay every phase/year',()=>{for(const t of C.TEAMS)for(const local of [false,true])for(const diff of ['easy','normal','hard']){const g=draft('flow06-'+t.id+'-'+local+'-'+diff,t.id,local,diff);assert(C.validate(g));const p=clone(C.poolFor(g).players),news=clone(g.news),forecast=clone(g.forecasts);C.runSeason(g);const first=clone(g.season),owner=clone(g.owner),fans=C.fanState(g).score;for(let n=1;n<=5;n++){assert(C.validate(clone(g)));assert.equal(g.career.years.length,n);if(n<5)C.nextSeason(g);}assert.throws(()=>C.nextSeason(g));assert.deepEqual(g.season,first);assert.deepEqual(g.owner,owner);assert.equal(C.fanState(g).score,fans);assert.deepEqual(g.news,news);assert.deepEqual(g.forecasts,forecast);assert.deepEqual(C.poolFor(g).players,p);for(const club of C.TEAMS)assert(C.quotaStatus(g,club.id).count>=1);assert.equal(C.careerReview(g).length,10);}});
test('counting stats, cumulative rates, team schedules and season affiliations reconcile',()=>{const g=finish(draft('records06'));for(const y of g.career.years){assert.equal(y.records.length,80);assert.equal(y.league.table.reduce((n,x)=>n+x.wins,0),720);for(const t of y.league.table)assert.equal(t.wins+t.losses,144);for(const r of y.records){checkStats(r.stats);checkStats(r.futures);if(r.stats.kind==='hitter')assert(r.stats.games+r.futures.games<=144);}for(const a of y.awards){const rec=y.records.find(r=>r.playerId===a.playerId);assert.equal(a.teamId,rec.teamId);assert(rec.stats.games>0);}}for(const s of g.picks){const h=C.Career.history(g.career,s.playerId);for(const key of ['stats','futures']){const total=C.Career.totalStats(h,key);checkStats(total);assert.equal(total.games,h.reduce((n,r)=>n+r[key].games,0));}for(let i=1;i<h.length;i++)if(h[i].route!=='released')assert.equal(h[i].startGrade,h[i-1].scoutReady);}});
test('healthy established players do not randomly disappear into the futures',()=>{const g=C.createGame('lg',false,'retention06'),p=C.poolFor(g).players.find(p=>p.role==='SP'),sel={label:'1R',round:1},tools=Object.fromEntries(Object.keys(p.trueTools).map(k=>[k,52]));let healthy=0,retained=0;for(let i=0;i<1000;i++){const rec=M.simulatePlayer({...p,trueTools:tools,potentialTools:Object.fromEntries(Object.keys(tools).map(k=>[k,60]))},sel,{seed:'retention-'+i},C.teamFor(g),90,{tools,route:'regular',scoutReady:50,publicTools:tools,performance:.3},2);if(!rec.limited){healthy++;retained+=rec.route==='regular';assert(rec.stats.games>0);assert.notEqual(rec.route,'futures');}}assert(retained/healthy>.8&&retained/healthy<.99);});
test('tool interventions affect relevant statistics without using overall-point shortcuts',()=>{const r=seed=>D.rng(seed),p={role:'OF'},base={contact:50,power:50,speed:50,defense:50,eye:50};const sum=(kind,key,delta,stat)=>{let s=0;for(let i=0;i<400;i++){const tools={...kind};tools[key]+=delta;s+=M.statsFor(p,130,tools,'regular',r('tool-'+i))[stat];}return s;};assert(sum(base,'power',15,'hr')>sum(base,'power',-10,'hr')*2);assert(sum(base,'contact',15,'hits')>sum(base,'contact',-10,'hits'));assert(sum(base,'speed',15,'sb')>sum(base,'speed',-10,'sb'));assert(sum(base,'eye',15,'bb')>sum(base,'eye',-10,'bb'));const sp={role:'SP'},tb={stuff:50,command:50,breaking:50,stamina:50};let lowBB=0,highBB=0,lowIP=0,highIP=0,lowK=0,highK=0;for(let i=0;i<400;i++){lowBB+=M.statsFor(sp,28,{...tb,command:35},'regular',r('sp-'+i)).bb;highBB+=M.statsFor(sp,28,{...tb,command:65},'regular',r('sp-'+i)).bb;lowIP+=M.statsFor(sp,28,{...tb,stamina:35},'regular',r('ip-'+i)).outs;highIP+=M.statsFor(sp,28,{...tb,stamina:65},'regular',r('ip-'+i)).outs;lowK+=M.statsFor(sp,28,{...tb,stuff:35},'regular',r('k-'+i)).k;highK+=M.statsFor(sp,28,{...tb,stuff:65},'regular',r('k-'+i)).k;}assert(highBB<lowBB);assert(highIP>lowIP);assert(highK>lowK);});
test('mature starter wins and slugger home runs have no V5 artificial caps',()=>{let maxW=0,maxHR=0,maxIP=0;for(let i=0;i<300;i++){const a=M.statsFor({role:'SP'},30,{stuff:65,command:65,breaking:60,stamina:60},'regular',D.rng('starP-'+i));const b=M.statsFor({role:'OF'},135,{contact:55,power:65,speed:45,defense:45,eye:50},'regular',D.rng('starH-'+i));maxW=Math.max(maxW,a.wins);maxIP=Math.max(maxIP,a.outs/3);maxHR=Math.max(maxHR,b.hr);checkStats(a);checkStats(b);}assert(maxW>=15);assert(maxIP>=160);assert(maxHR>=30);});
test('trait-specific development carries tools forward and is not four identical boosts',()=>{const g=finish(draft('growth06'));assert(g.career.years.flatMap(y=>y.records).some(r=>r.growth>2));const p=C.getPlayer(g,g.picks[0].playerId),s=g.career.players[p.id];const changes=Object.keys(p.trueTools).map(k=>D.round(s.tools[k]-p.trueTools[k],1));assert(new Set(changes).size>1);for(const sel of g.picks){const p=C.getPlayer(g,sel.playerId),s=g.career.players[p.id];for(const k of Object.keys(s.tools))assert(s.tools[k]<=p.potentialTools[k]+.001);}});
test('restore rebuilds derived data from inputs and rejects edited inputs',()=>{const g=finish(draft('tamper06'));const honest=JSON.stringify(g);
 // Derived data is never trusted: edits are discarded and the honest game is rebuilt.
 for(const change of [x=>x.scoutReport.candidates[0].playerId='p999',x=>x.clubPlans.lg.staff.style='other',x=>x.forecasts[0].picks[0].playerId='p999',x=>x.career.years[0].records[0].stats.games++,x=>x.career.players[x.picks[0].playerId].tools={},x=>x.owner.score++,x=>x.news[0].headline='edited']){const bad=clone(g);change(bad);assert.equal(JSON.stringify(C.restore(bad)),honest);}
 // Inputs are checked: wrong version, a CPU pick the AI would not make, an illegal pick, too many seasons, unknown GM answer.
 const cpu=g.picks.findIndex(s=>s.teamId!=='lg'),mine=g.picks.findIndex(s=>s.teamId==='lg');
 for(const change of [x=>x.version=5,x=>x.picks[cpu].playerId=x.picks.at(-1).playerId,x=>x.picks[mine].playerId='p999',x=>x.career.years.push(x.career.years[0]),x=>x.gmChoice='other',x=>x.seed='',x=>x.cursor=3]){const bad=clone(g);change(bad);assert.equal(C.restore(bad),null);assert(!C.validate(bad));}
 assert(!C.validate(null));assert(!C.validate({}));});
test('every new sort handles mixed positions and nulls in both directions',()=>{const g=C.createGame('lg',false,'sort06'),ps=C.poolFor(g).players,t=C.teamFor(g);for(const key of Object.keys(C.rules.SORTS))for(const dir of ['asc','desc']){const sorted=C.rules.sortPlayers(ps,key,dir,t);let seenNull=false,last=null;for(const p of sorted){const v=C.rules.sortValue(p,key,t);if(v==null)seenNull=true;else{assert(!seenNull);if(last!=null)assert(dir==='asc'?v>=last:v<=last);last=v;}}}});
