/* Reproducible all-AI tuning audit; game experiments, NOT empirical KBO statistics. */
const C=require('../src/core/engine.js'),D=require('../src/core/prospects.js'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const N=Number(process.env.BALANCE_SEEDS||200),results=[],pct=(a,b)=>D.round(a*100/(b||1),2);
for(const difficulty of ['easy','normal','hard']){
 const rounds=Array.from({length:8},(_,round)=>({round,n:0,debut:0,regular:0,fv:0,fv60:0})),years=Array.from({length:5},(_,i)=>({year:2027+i,n:0,debut:0,regular:0}));
 const trans={n:0,retained:0,futures:0,healthySame:0,healthyRetained:0,healthyFutures:0};let n=0,near5=0,fvAchieved=0,sumScore=0,teams=0,maxW=0,maxHR=0,maxIP=0,tenW=0,twentyHR=0,regularSP=0,spW=0,spIP=0,regularHit=0,hitHR=0,hitG=0,trade=0,release=0,mlbPools=0,rareFV=0;
 for(let i=0;i<N;i++){
  const g=C.createGame('kiwoom',i%2===0,'balance06-'+i,difficulty),pool=C.poolFor(g);mlbPools+=pool.players.some(p=>p.pathway==='MLB 경험 복귀');rareFV+=pool.players.filter(p=>p.scoutCeiling>=60).length;
  C.openScouting(g);C.beginDraft(g);while(g.phase==='draft')C.addPick(g,C.aiChoice(g).id);C.chooseGM(g,['immediate','development','needs'][i%3]);C.runSeason(g);while(g.career.years.length<5)C.nextSeason(g);
  for(const s of g.picks){const p=C.getPlayer(g,s.playerId),h=C.Career.history(g.career,p.id),r=rounds[s.round],st=g.career.players[p.id];r.n++;r.debut+=h[0].stats.games>0;r.regular+=h[0].route==='regular';r.fv+=p.scoutCeiling;r.fv60+=p.scoutCeiling>=60;n++;near5+=p.upside-st.ability<=5;fvAchieved+=st.scoutReady>=p.scoutCeiling;
   for(let j=0;j<5;j++){const rec=h[j],stats=rec.stats,y=years[j];y.n++;y.debut+=stats.games>0;y.regular+=rec.route==='regular';if(j&&h[j-1].route==='regular'){trans.n++;trans.retained+=rec.route==='regular';trans.futures+=rec.route==='futures';if(!rec.limited&&rec.teamId===h[j-1].teamId){trans.healthySame++;trans.healthyRetained+=rec.route==='regular';trans.healthyFutures+=rec.route==='futures';}}
    if(p.role==='SP'){maxW=Math.max(maxW,stats.wins);maxIP=Math.max(maxIP,stats.outs/3);tenW+=stats.wins>=10;if(j>=2&&rec.route==='regular'){regularSP++;spW+=stats.wins;spIP+=stats.outs/3;}}
    if(stats.kind==='hitter'){maxHR=Math.max(maxHR,stats.hr);twentyHR+=stats.hr>=20;if(j>=2&&rec.route==='regular'){regularHit++;hitHR+=stats.hr;hitG+=stats.games;}}
   }
  }
  for(const ev of g.career.events){trade+=ev.type==='trade';release+=ev.type==='release';if(ev.type==='release'){assert(ev.year>=2029&&ev.year<=2030);const rec=g.career.years.find(y=>y.year===ev.year).records.find(r=>r.playerId===ev.playerIds[0]),old=g.career.years.find(y=>y.year===ev.year-1).records.find(r=>r.playerId===ev.playerIds[0]);assert(rec.age>=23&&rec.stats.games===0&&old.stats.games===0&&rec.scoutReady<40);}assert(ev.year<2031);}
  for(const t of C.careerReview(g)){sumScore+=t.score;teams++;}
 }
 const summary=r=>({round:r.round,year:r.year,sample:r.n,debutPct:pct(r.debut,r.n),regularPct:pct(r.regular,r.n),...(r.fv!=null?{meanFV:D.round(r.fv/r.n,2),fv60plusPct:pct(r.fv60,r.n)}:{})});
 const row={difficulty,drafts:N,players:n,playerSeasons:n*5,rounds:rounds.map(summary),years:years.map(summary),transitions:{sample:trans.n,regularRetentionPct:pct(trans.retained,trans.n),toFuturesPct:pct(trans.futures,trans.n),healthySameTeamSample:trans.healthySame,healthyRetentionPct:pct(trans.healthyRetained,trans.healthySame),healthyToFuturesPct:pct(trans.healthyFutures,trans.healthySame)},growth:{within5InternalCeilingPct:pct(near5,n),publicFVReachedPct:pct(fvAchieved,n),denominator:'all drafted, including released with last stored ability; grades are V6 20–80, not V5 100-point equivalents'},stats:{maxSPWins:maxW,maxSPIp:D.round(maxIP,2),tenWinSeasons:tenW,maxHitterHR:maxHR,twentyHRSeasons:twentyHR,matureRegularSPMeanWins:D.round(spW/regularSP,2),matureRegularSPMeanIP:D.round(spIP/regularSP,2),matureRegularHitterMeanHR:D.round(hitHR/regularHit,2),matureRegularHitterMeanGames:D.round(hitG/regularHit,2)},meanFinalScore:D.round(sumScore/teams,2),meanTrades:D.round(trade/N,2),meanReleases:D.round(release/N,2),mlbPools,meanFV60plusPer200:D.round(rareFV/N,2)};
 results.push(row);console.log(JSON.stringify(row,null,2));
 assert(row.rounds[1].debutPct>=65&&row.rounds[1].debutPct<=96,'first-round trial opportunities');assert(row.rounds[1].regularPct>=10&&row.rounds[1].regularPct<=45,'first-round establishment remains uncertain');assert(row.transitions.healthyRetentionPct>=78&&row.transitions.healthyRetentionPct<=98,'established role continuity');assert(row.transitions.healthyToFuturesPct<3,'no random healthy demotion');assert(row.growth.within5InternalCeilingPct>=30&&row.growth.within5InternalCeilingPct<=95,'growth gap closes, not guaranteed');assert(row.stats.maxSPWins>=15&&row.stats.maxHitterHR>=30);assert(tenW>100&&twentyHR>100,'high counting stats occur in real generated cohorts');assert(row.stats.matureRegularSPMeanIP>=130&&row.stats.matureRegularSPMeanIP<=180);assert(row.stats.matureRegularHitterMeanHR>=6&&row.stats.matureRegularHitterMeanHR<=18);assert(row.meanFV60plusPer200<12);assert(row.rounds[3].fv60plusPct<10);assert(row.rounds[7].meanFV<row.rounds[1].meanFV-8);assert(row.meanFinalScore>=50&&row.meanFinalScore<=88);assert(trade>0);
}
const report={notice:'V0.6 fictional all-AI balance audit. Thresholds are game design targets, not official KBO statistics. V5 vs V6 use different candidate generation and grade meanings; no causal same-player comparison is claimed.',drafts:N*3,results};fs.writeFileSync(path.join(__dirname,'v06-balance-results.json'),JSON.stringify(report,null,2)+'\n');console.log('PASS V0.6 balance checks');
