/* UI for the self-contained DRAFT ROOM prototype. */
(function(){
  'use strict';
  const C=window.DraftCore,V=window.DraftView04, $=s=>document.querySelector(s), STORE='draft-room-kbo-v4-spotlight';
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let difficulty='normal',sortDir='asc';
  let selectedTeam='kiwoom',local=false,game=null,selectedPlayer=null,roleFilter='ALL',pathwayFilter='ALL',tierFilter='ALL',query='',sort='rank',onlyStars=false,stars=new Set(),modal=null,lastFocus=null,toastTimer;
  let storageAvailable=true;
  try {
    const saved=JSON.parse(localStorage.getItem(STORE)||'null');
    if(saved){if(Object.hasOwn(C.rules.DIFFICULTIES,saved.difficulty))difficulty=saved.difficulty;if(Object.hasOwn(C.teamById,saved.selectedTeam))selectedTeam=saved.selectedTeam;local=saved.local===true;stars=new Set((Array.isArray(saved.stars)?saved.stars:[]).filter(id=>typeof id==='string'&&Object.hasOwn(C.playerById,id)));if(C.validate(saved.game)){game=saved.game;local=game.local;difficulty=game.difficulty;selectedTeam=game.teamId;if(game.phase==='draft')C.advanceToUser(game);}}
    localStorage.setItem(STORE+'-check','1');localStorage.removeItem(STORE+'-check');
  }catch(e){storageAvailable=false;}
  function save(){try{localStorage.setItem(STORE,JSON.stringify({selectedTeam,local,difficulty,game,stars:[...stars]}));}catch(e){storageAvailable=false;}}
  function badge(t,size=''){return `<span class="team-mark" style="background:${t.color};${size}">${t.mark}</span>`;}
  function tag(text,cls=''){return `<span class="tag ${cls}">${escape(text)}</span>`;}
  function metric(value,label){return `<div class="metric"><b>${escape(value)}</b><span>${escape(label)}</span></div>`;}
  function avg(n){return n==null?'—':n.toFixed(3).replace(/^0/,'');}
  function labelRound(slot){return slot?.round===0?'지역 1차 지명':`${slot?.round||1}라운드 지명`;}
  function team(){return C.teamById[game?.teamId||selectedTeam];}
  function stage(){return game?({preview:2,draft:3,interviews:4,season:5,owner:6}[game.phase]):1;}
  function setCandidate(){
    if(!game||game.phase!=='draft')return;
    const list=C.available(game);if(!list.some(p=>p.id===selectedPlayer))selectedPlayer=list[0]?.id||null;
  }
  function notify(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').hidden=false;toastTimer=setTimeout(()=>{$('#toast').hidden=true;},3200);}
  function render(){
    setCandidate();
    $('#steps').innerHTML=['구단 선택','언론 예상','드래프트','인터뷰','루키 시즌','구단주 평가'].map((name,i)=>`<div class="step ${stage()===i+1?'active':stage()>i+1?'done':''}" ${stage()===i+1?'aria-current="step"':''}><b>${stage()>i+1?'✓':String(i+1).padStart(2,'0')}</b>${name}</div>`).join('');
    $('#reset-game').hidden=!game;
    $('#main').innerHTML=(game?V.infoBar(game):'')+(!game?renderSetup():game.phase==='preview'?V.forecasts(game):game.phase==='draft'?renderDraft():game.phase==='interviews'?renderInterviews():game.phase==='season'?renderSeason():renderOwner());
    $('#storage-status').textContent=storageAvailable?'이 브라우저에 진행 상태 자동 저장':'현재 환경에서는 자동 저장이 제한됩니다';
    save();
  }
  function renderSetup(){const t=team();return `
    <section class="hero fade-in"><div class="hero-copy"><span class="eyebrow">THE NEXT FRANCHISE PLAYER</span><h1>우리 팀의 내일을<br>지명하는 시간.</h1><p>기록과 성장 배경을 살피며 기다릴 가치가 있는 선수를 선택합니다.<br>첫해의 무대가 퓨처스여도, 성장은 계속됩니다.</p></div><div class="hero-numbers"><div class="hero-number"><b>10</b><span>구단</span></div><div class="hero-number"><b>200</b><span>매 판 새로운 유망주</span></div><div class="hero-number"><b>5<span style="display:inline;font-size:16px;color:#fff"> R</span></b><span>${local?'지역 1차 + 본 지명':'라이트 드래프트'}</span></div></div></section><p class="draft-date">가상 ${C.ENTRY_YEAR} 신인 드래프트 · 지명 및 만 나이 기준일 ${C.DRAFT_DATE} · 5라운드 / 고졸 80%</p>
    <section class="build-note" aria-label="v0.4 변경 사항"><strong>BUILD 0.4 · IN THE SPOTLIGHT</strong><span>난이도 · 언론 모의 드래프트</span><span>지명 뉴스 · 커뮤니티</span><span>기록별 정렬 · 단장 인터뷰 · 팬심</span></section>
    <section class="difficulty-settings panel"><h2>드래프트 난이도</h2><div class="difficulty-options">${Object.entries(C.rules.DIFFICULTIES).map(([id,c])=>`<button data-action="difficulty" data-id="${id}" aria-pressed="${difficulty===id}" class="difficulty-option ${difficulty===id?'selected':''}"><strong>${c.name}</strong><span>${c.hint}</span></button>`).join('')}</div><p>선수 능력과 성장 확률은 동일합니다. 공개 평가의 관측 오차도 같으며, 조언의 상세함과 AI의 판단 방식이 달라집니다.</p></section>
    <div class="section-head"><h2>어느 구단의 미래를 맡으시겠습니까?</h2><p>가상 직전 시즌 순위 역순 · 지명 순서</p></div>
    <div class="team-layout"><section class="teams" aria-label="구단 선택">${C.TEAMS.map((club,i)=>`<button class="team-card ${club.id===selectedTeam?'selected':''}" data-action="team" data-id="${club.id}" aria-pressed="${club.id===selectedTeam}"><span class="pick-order">${String(i+1).padStart(2,'0')} PICK</span>${badge(club)}<span><span class="team-name">${club.name}</span><span class="team-meta">${club.rank}위 · ${club.record}</span></span></button>`).join('')}</section>
    <aside class="panel team-detail"><div class="pad"><span class="eyebrow muted">YOUR CLUB REPORT</span><div class="team-detail-header">${badge(t,'width:46px;height:46px')}<div><h2>${t.short}</h2><p class="tiny muted">${t.region} · 가상 시즌 ${t.rank}위</p></div></div><div class="info-pair"><label>전력의 강점</label><strong>${t.strong}</strong></div><div class="info-pair"><label>보강이 필요한 부분</label><strong>${t.weak}</strong></div><div class="info-pair"><label>보강 우선순위</label><div class="need-list">${t.needs.map((x,i)=>tag(`${i+1} ${C.ROLES[x]}`,i===0?'green':'')).join('')}</div></div><p class="goal">“${t.goal}”</p><button class="primary" data-action="start">${t.short} 단장으로 시작 <span class="arrow">→</span></button><p class="tiny muted" style="text-align:center;margin-top:10px">${local?'지역 1차 포함 6명 지명':'5라운드 · 총 5명 지명'} · 약 8분</p></div></aside></div>
    <section class="panel settings"><div class="settings-line"><div><h3>지역 1차 지명</h3><p>본 드래프트에 앞서 연고 지역의 고교 유망주를 우선 지명합니다.</p></div><label class="toggle-wrap"><span>${local?'ON':'OFF'}</span><span class="switch"><input type="checkbox" id="local-toggle" aria-label="지역 1차 지명 사용" ${local?'checked':''}><span class="switch-track"></span></span></label></div><div class="rule-note">${local?'<strong>ON 규칙</strong> · 각 구단이 지역 고졸 후보 1명을 지명한 후, 전국 단위 5라운드를 진행합니다. 서울 3개 구단은 같은 후보군에서 현재 설정된 지명 순서대로 선택합니다.':'<strong>OFF 규칙 · 기본값</strong> · 모든 후보를 대상으로 가상 직전 시즌 순위의 역순으로 5라운드를 진행합니다. 매 라운드 순서는 같으며, 추첨이나 스네이크 방식은 없습니다.'}<br>※ 과거 제도의 연도별 연고권·서울 순번 순환·전국 지명 예외를 재현하지 않은 간소화 규칙입니다. 설정은 게임 시작 전에만 변경할 수 있습니다. 출생지가 아닌 현재 고교·고교 연령 BC 소속 지역으로 판정하며 대졸·독립·해외파는 제외합니다.</div></section>
    <p class="footnote">PROTOTYPE v0.4 · 구단명 외 선수·학교·기록·순위·전력·대회 경력은 모두 게임용 가상 데이터입니다. 실제 선수 평가나 공식 KBO 게임이 아닙니다. 실제 전체 라운드 대신 5라운드로 축소했습니다.</p>`;}
  function renderDraft(){const t=team(),slot=game.schedule[game.cursor],mine=C.myPicks(game);return `
    <section class="turn-head"><div><span class="eyebrow" style="margin:0"><i class="live-dot"></i> DRAFT LIVE <span class="muted">/ YOUR TURN</span></span><h1>${labelRound(slot)}, ${t.short}의 선택</h1><p>${t.goal} <span class="mobile-detail">선수 선택 → 아래 프로필 확인 → 지명하기</span></p></div><div class="turn-count"><b>${mine.length}<span class="muted" style="font-size:14px"> / ${game.local?6:5}</span></b><p>우리 팀 지명</p><div class="progress-track"><span style="width:${game.cursor/game.schedule.length*100}%"></span></div></div></section>
    <div class="ticker" aria-label="현재 라운드 지명 현황">${C.TEAMS.map(club=>{const picked=game.picks.find(s=>s.round===slot.round&&s.teamId===club.id);return `<div class="ticker-item ${club.id===game.teamId?'current':''}"><span class="ticker-name"><i class="club-dot" style="background:${club.id===game.teamId?'var(--lime)':club.color}"></i>${club.short}${club.id===game.teamId?'<small>YOU</small>':''}</span><span class="ticker-player">${picked?C.playerById[picked.playerId].name:club.id===game.teamId?'지명 중 …':'대기'}</span></div>`;}).join('')}</div>
    ${slot.round===0?`<p class="notice">지역 1차 지명 · ${t.region} 지역의 고졸 후보만 표시됩니다. 지명이 끝나면 모든 지역의 미지명 선수가 본 드래프트 후보가 됩니다. <strong>간소화된 가상 규칙</strong>입니다.</p>`:''}
    <div class="draft-layout"><div><section class="panel"><div class="board-head"><div class="board-title"><h2>스카우팅 보드 <span class="tiny muted" id="candidate-count"></span></h2><span class="tag">${slot.round===0?'지역 후보':'전국 후보'}</span></div><div class="search-row"><label class="sr-only" for="search">선수명 또는 학교 검색</label><input id="search" placeholder="선수명 · 학교 검색" value="${escape(query)}" autocomplete="off"><label class="sr-only" for="sort">후보 정렬</label><select id="sort">${V.sortOptions(sort)}</select><button class="ghost sort-direction" data-action="sort-direction" aria-label="정렬 방향 전환">${sortDir==='asc'?'↑ 오름차순':'↓ 내림차순'}</button></div><div class="chips">${[['ALL','전체'],...Object.entries(C.ROLES)].map(([id,name])=>`<button class="chip ${roleFilter===id?'active':''}" data-action="role" data-id="${id}" aria-pressed="${roleFilter===id}">${name}</button>`).join('')}<button class="chip ${onlyStars?'active':''}" data-action="only-stars" aria-pressed="${onlyStars}">★ 관심</button></div><div class="search-row" style="margin:10px 0 0"><label class="sr-only" for="pathway">출신 구분</label><select id="pathway" style="width:100%">${['ALL','고졸','대졸','독립구단','해외파'].map(v=>`<option value="${v}" ${pathwayFilter===v?'selected':''}>${v==='ALL'?'출신 구분 전체':v}</option>`).join('')}</select><label class="sr-only" for="tier">야구부 평판</label><select id="tier" style="width:100%">${['ALL','명문','강호','중견','약소','미분류'].map(v=>`<option value="${v}" ${tierFilter===v?'selected':''}>${v==='ALL'?'야구부 평판 전체':v}</option>`).join('')}</select></div></div><div class="roster-columns"><span>순위</span><span>선수 / 출신</span><span>정렬값</span><span>보강 적성</span></div><div class="roster" id="roster">${renderRows()}</div><div class="board-bottom">선택한 항목의 값으로 정렬합니다. 해당하지 않는 기록(—)은 양방향 모두 마지막에 표시합니다. 이닝은 아웃 수로 비교합니다. 서로 다른 리그와 표본의 단순 비교에는 주의해야 합니다.</div></section>${renderLog()}</div><div><div id="profile">${renderProfile()}</div>${renderMyPicks()}</div></div>`;}
  function filtered(){if(!game)return [];return C.rules.sortPlayers(C.available(game).filter(p=>(roleFilter==='ALL'||p.role===roleFilter)&&(pathwayFilter==='ALL'||p.pathway===pathwayFilter)&&(tierFilter==='ALL'||(p.schoolTier||'미분류')===tierFilter)&&(!onlyStars||stars.has(p.id))&&(!query||(`${p.name} ${p.pathText} ${p.region} ${p.birthplace}`).includes(query.trim()))),sort,sortDir,team());}
  function renderRows(){const list=filtered();return list.length?list.map(p=>`<button class="player-row ${selectedPlayer===p.id?'selected':''}" data-action="player" data-id="${p.id}" aria-pressed="${selectedPlayer===p.id}" aria-label="${p.name} ${C.ROLES[p.role]} 프로필"><span class="rank">${String(p.rank).padStart(2,'0')}</span><span><span class="p-name">${stars.has(p.id)?'★ ':''}${p.name} <span style="font-size:9px;font-weight:500;color:var(--muted)">${p.throwHand}투${p.batHand}타</span></span><span class="p-meta">${C.ROLES[p.role]} · ${p.school} · ${p.pathway}</span></span><span><span class="p-stat">${V.sortedStat(p,sort,team()).value}</span><span class="p-stat-label">${V.sortedStat(p,sort,team()).label}</span></span>${tag(C.fitLabel(p,team()),C.fit(p,team())>=80?'green':'')}</button>`).join(''):`<div class="empty">조건에 맞는 후보가 없습니다.<br><button class="ghost" data-action="clear-filters" style="margin-top:12px">필터 초기화</button></div>`;}
  function refreshRows(){const roster=$('#roster');if(roster){const y=roster.scrollTop;roster.innerHTML=renderRows();roster.scrollTop=y;$('#candidate-count').textContent=filtered().length+'명';}}
  function renderBiography(p){const cls={명문:'prestige',강호:'strong',중견:'middle',약소:'small'}[p.schoolTier]||'unknown';return `<section class="bio-panel" aria-label="선수 성장 배경"><div class="bio-grid"><div><span>생년월일</span><strong>${p.birthday}</strong></div><div><span>출생지 · 고교 연고와 별도</span><strong>${p.birthplace}</strong></div><div><span>현재·최종 소속 야구부 평판</span><strong class="tier-label ${cls}">${p.schoolTier||'미분류'}</strong></div><div><span>지역 1차 자격</span><strong>${p.regionalEligible?p.regionalRegion+' 대상':'대상 아님'}</strong></div></div><p class="bio-note">${p.regionalReason}</p><details class="history"><summary>진학·활동 이력 <span>⌄</span></summary><p class="path-text">${p.pathText}</p><ol>${p.history.map(h=>`<li><strong>${h.name}</strong><span>${h.start.slice(0,7)} ~ ${h.end?h.end.slice(0,7):'현재'} · ${h.status}</span>${h.note?`<small>${h.note}</small>`:''}</li>`).join('')}</ol></details>${p.schoolTier?`<p class="school-context">야구부 평판과 ${p.schoolStyle} 성향을 반영합니다. 평판은 평균적인 준비도와 팀 성적에 영향을 주지만 개인의 잠재력을 제한하지는 않습니다.${p.schoolTournament?'<br>가상 '+p.schoolTournament.event+' · '+p.schoolTournament.result:''}</p>`:'<p class="school-context">독립구단·해외 소속에는 국내 학교의 야구부 평판 등급을 적용하지 않습니다.</p>'}</section>`;}
  function renderProfile(){const p=C.playerById[selectedPlayer];if(!p)return '<div class="panel empty">프로필을 확인할 후보를 선택하십시오.</div>';const t=team(),r=p.record;const metrics=r.kind==='pitcher'?metric(r.era.toFixed(2),'평균자책점')+metric(C.innings(r.outs),'이닝')+metric(r.k,'탈삼진')+metric(r.bb,'볼넷'):metric(avg(r.avg),'타율')+metric(r.ops.toFixed(3),'OPS')+metric(r.hr,'홈런')+metric(r.sb,'도루');return `
    <article class="panel player-card"><div class="profile-header"><div class="profile-top"><div><span class="eyebrow muted" style="font-size:9px;margin-bottom:5px">SCOUT REPORT / NO.${String(p.rank).padStart(3,'0')}</span><h2>${p.name}</h2><p>${p.school} · ${p.pathway} · ${p.age}세 (만 나이)</p><p style="margin-top:5px">${p.currentInstitution.kind==='hs-club'?'고교 연령 클럽':p.qualification} · ${p.personality}</p></div><div class="jersey">${String(p.rank).padStart(2,'0')}</div></div><div class="profile-tags">${tag(C.ROLES[p.role])}${tag(`${p.height}cm / ${p.weight}kg`)}${tag(`${p.throwHand}투${p.batHand}타`)}${tag(p.archetype,'green')}</div></div>
    <div class="profile-body">${renderBiography(p)}<div class="section-head" style="margin:0"><span class="mini-heading">지명 전 시즌 기록</span><button class="ghost" style="font-size:10px;padding:5px 8px" data-action="star" data-id="${p.id}" aria-pressed="${stars.has(p.id)}">${stars.has(p.id)?'★ 관심 해제':'☆ 관심 등록'}</button></div><div class="metric-grid">${metrics}</div><p class="context-note">${p.pathway==='고졸'?'고교 대회 합산':p.pathway==='대졸'?'대학 리그·대회 합산':p.pathway==='독립구단'?'독립리그':'해외 소속 리그'} · ${r.games}경기${r.kind==='hitter'?' · '+r.pa+'타석 · '+r.rbi+'타점 · '+r.runs+'득점':' · '+r.wins+'승'}<br>${C.DRAFT_DATE} 기준입니다. 서로 다른 경기 수준의 기록은 단순 비교에 주의해야 합니다.${r.kind==='pitcher'?'<br>이닝의 .1 / .2는 각각 ⅓ / ⅔이닝입니다.':''}</p>
    ${V.scoutTools(p)}<span class="mini-heading">경험 & 스카우팅</span><div class="awards">${p.awards.length?p.awards.map(x=>tag('✦ '+x,'orange')).join(''):tag('주요 대표팀·우승 경력 없음')}${r.kind==='pitcher'?tag('최고 '+p.velocity+'km/h','dark'):''}</div><div class="scout-row"><b>강점</b><span>${p.strength}</span></div><div class="scout-row risk"><b>과제</b><span>${p.weakness}</span></div><div class="outlook"><span>프로 적응 전망<br><strong>${C.outlook(p)}</strong></span><span>성장 기대 · 비확정<br><strong>${C.upsideLabel(p)}</strong></span></div><div class="fit-box"><strong>${t.short} 적합도 · ${C.fitLabel(p,t)}</strong><br>${C.fit(p,t)>=60?`보강 우선순위 ${t.needs.indexOf(p.role)+1}번, ${C.ROLES[p.role]} 자원입니다.`:'주요 보강 포지션은 아닙니다. 재능 우선 지명을 고려할 수 있습니다.'}</div><details class="advice" open><summary><span class="advisor-mark">SC</span> 스카우트 팀장의 조언 <span class="muted">⌄</span></summary><ul>${C.scoutAdvice(p,game).lines.map(line=>`<li>${escape(line)}</li>`).join('')}</ul><p>공개된 스카우팅과 현재 후보군에 근거한 의견 · 정답 아님</p></details><button class="primary lime" data-action="pick" data-id="${p.id}">${p.name} 지명하기 <span class="arrow">→</span></button></div></article>`;}
  function renderMyPicks(){const mine=C.myPicks(game);return `<section class="panel my-picks"><h3>우리 팀 지명 보드 <span class="muted">${mine.length}/${game.local?6:5}</span></h3>${mine.length?mine.map(s=>{const p=C.playerById[s.playerId];return `<div class="my-pick">${tag(s.label)}<strong>${p.name}</strong><span>${C.ROLES[p.role]}</span><span class="muted">${p.school}</span></div>`;}).join(''):'<p class="tiny muted">첫 번째 유니폼의 주인공을 기다립니다.</p>'}</section>`;}
  function renderLog(){return `<details class="panel log"><summary>전체 구단 지명 기록 <span class="muted">${game.picks.length}명</span></summary><div class="log-list">${game.picks.length?game.picks.map(s=>{const p=C.playerById[s.playerId],t=C.teamById[s.teamId];return `<div class="log-item"><span class="muted">${s.label}</span><strong style="color:${t.color}">${t.short}</strong><span>${p.name} · ${C.ROLES[p.role]}</span>${s.teamId===game.teamId?tag('YOU','green'):''}</div>`;}).join(''):'<p class="tiny muted">아직 지명된 선수가 없습니다.</p>'}</div></details>`;}
  function resultHero(eyebrow,title,desc){return `<section class="hero fade-in"><div class="hero-copy"><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${desc}</p></div><div class="hero-numbers"><div class="hero-number"><b>${team().short}</b><span>${game.local?'지역 1차 ON':'지역 1차 OFF'} · ${C.myPicks(game).length}명 지명</span></div></div></section>`;}
  function renderInterviews(){return `${resultHero('DRAFT COMPLETE / FIRST WORDS','새로운 유니폼, 첫 번째 인사.','드래프트가 끝났습니다. 단장의 방향을 설명하고, 신인들의 이야기를 들어볼 시간입니다.')} ${V.gm(game)}<div class="section-head"><h2>신인 선수 입단 인터뷰</h2><p>선수의 출신과 성장 전망에 따른 가상 인터뷰</p></div><section class="quote-grid">${C.myPicks(game).map(s=>{const p=C.playerById[s.playerId];return `<article class="panel quote-card"><div class="quote-name">${tag(s.label,'green')}${tag(C.ROLES[p.role])}</div><h3>${p.name}</h3><p class="tiny muted">${p.pathText}</p><blockquote>${C.interview(p,s,game,'ceremony')}</blockquote><div class="scout-row"><b>육성</b><span>${C.outlook(p)} · ${p.personality}</span></div></article>`;}).join('')}</section>${renderLog()}<div class="section-action"><button class="primary" data-action="simulate" ${game.gmChoice?'':'disabled'}>1년 뒤, 루키 시즌 성적 확인 <span class="arrow">→</span></button><p>${game.gmChoice?'실력 · 출전 기회 · 성장 · 컨디션 변동을 함께 반영합니다.':'위 단장 인터뷰의 답변을 먼저 확정해야 합니다.'}</p></div>`;}
  function statMetrics(v){return v.kind==='pitcher'?metric(v.games,'경기')+metric(C.innings(v.outs),'이닝')+metric(v.era==null?'—':v.era.toFixed(2),'ERA')+metric(v.k,'탈삼진')+metric(v.wins,'승')+metric(v.bb,'볼넷'):metric(v.games,'경기')+metric(avg(v.avg),'타율')+metric(v.ops==null?'—':v.ops.toFixed(3),'OPS')+metric(v.hr,'홈런')+metric(v.rbi,'타점')+metric(v.sb,'도루');}
  function renderSeasonCards(){return `<section class="season-list">${game.season.map(s=>{const p=C.playerById[s.playerId],v=s.stats,f=s.futures;return `<article class="panel season-card"><div class="season-header"><div class="quote-name">${tag(s.label,'green')} ${tag(C.ROLES[p.role])} ${tag(s.routeLabel,s.route==='regular'?'orange':'')}${s.route==='regular'&&Number(s.label[0])>=4?tag('후반 지명의 반전','lime'):''}</div><h3>${p.name}</h3><p class="tiny muted">${p.school} · ${p.pathway}<br>입단 당시 계획: ${s.target}</p></div><div class="season-body"><span class="mini-heading">1군 정규시즌 기록</span>${v.games?`<div class="metric-grid">${statMetrics(v)}</div><p class="context-note">${v.kind==='hitter'?v.pa+'타석':v.holds+'홀드 · '+v.saves+'세이브'} · ${s.route==='cameo'?'표본이 작습니다. 성적보다 경험에 주목할 필요가 있습니다.':'첫해 성적만으로 미래를 단정할 수는 없습니다.'}</p>`:'<div class="no-debut"><b>1군 미데뷔</b><p>첫해를 퓨처스에서 보냈습니다.<br>기록 없음은 0점 성적표가 아닙니다.</p></div>'}<p class="season-note">${s.note}</p><div class="futures-block"><h4>퓨처스리그 기록 <span class="tag">육성 리포트</span></h4><div class="metric-grid">${statMetrics(f)}</div><p class="context-note">${f.kind==='hitter'?f.pa+'타석 · ':''}1군과 경기 수준이 다르므로 숫자의 직접 비교에는 주의가 필요합니다.</p></div><div class="growth"><span>↗ ${s.growthLabel}</span><em>계획 이행 ${s.planScore}점</em></div><p class="development-focus">${s.developmentNote}</p></div></article>`;}).join('')}</section>`;}
  function renderSeason(){const major=game.season.filter(s=>s.stats.games>0).length,regular=game.season.filter(s=>s.route==='regular').length;return `${resultHero('ONE YEAR LATER / THE LONG GAME','성장은, 보이지 않는 곳에서도.','첫해의 무대는 저마다 다릅니다. 1군 기록이 없는 선수도 퓨처스에서 어떤 과제를 해결했는지 확인할 수 있습니다.')}<div class="season-summary"><div><b>${game.season.length}</b><span>우리 팀 신인</span></div><div><b>${game.season.length-major}</b><span>퓨처스 전념</span></div><div><b>${major}</b><span>1군 경험 · 안착 포함</span></div><div><b>${regular}</b><span>그중 1군 안착</span></div></div><div class="section-head"><h2>루키 시즌 · 1군과 퓨처스</h2><p>같은 게임에서는 결과 고정</p></div><p class="season-count-note">준비도와 적응, 출전 기회가 1군 진입을 좌우합니다. 지명 라운드가 능력치를 직접 깎지는 않습니다. 드문 반전도 있지만, 대부분은 기다림이 필요합니다.</p>${renderSeasonCards()}<p class="footnote">기록은 간단한 게임용 모델의 시뮬레이션이며 실제 KBO 성적 예측이 아닙니다. 이닝의 .1 / .2는 각각 ⅓ / ⅔이닝입니다.</p><div class="section-action"><button class="primary" data-action="owner">구단주 면담실로 <span class="arrow">→</span></button><button class="ghost" data-action="interviews" style="margin-top:12px">입단 인터뷰 다시 보기</button></div>`;}
  function renderOwner(){const o=game.owner;return `${resultHero('OWNER’S OFFICE / FINAL REVIEW','단장님, 수고하셨습니다.','보강 과제, 첫해 육성 계획, 미래 가치. 1군 미데뷔만으로 신인을 실패라고 평가하지 않습니다.')}<section class="owner-layout"><div class="grade-panel"><span class="eyebrow">DRAFT EVALUATION</span><div class="grade-letter">${o.grade}</div><div class="score">${o.score} <span class="muted">/ 100</span></div><p>${o.grade==='A'?'현재와 미래를 함께 채운 지명':o.grade==='B'?'방향이 보이는 유망한 지명':o.grade==='C'?'성장과 활용이 더 필요한 지명':'보강 전략을 돌아볼 지명'}</p></div><div class="panel pad"><div class="score-row"><div class="score-label"><strong>보강 과제 달성 <small>40%</small></strong><b>${o.needScore}점</b></div><div class="score-track"><div class="score-fill" style="width:${o.needScore}%"></div></div></div><div class="score-row"><div class="score-label"><strong>첫해 계획 이행 <small>25%</small></strong><b>${o.production}점</b></div><div class="score-track"><div class="score-fill" style="width:${o.production}%"></div></div></div><div class="score-row"><div class="score-label"><strong>미래 가치 · 성장 <small>35%</small></strong><b>${o.future}점</b></div><div class="score-track"><div class="score-fill" style="width:${o.future}%"></div></div></div><div class="owner-quote"><span class="eyebrow">MESSAGE FROM THE OWNER</span>“${o.text}”<p class="tiny muted" style="margin-top:10px">${o.missing.length?'남은 보강 과제: '+o.missing.join(' · '):'세 가지 우선 보강 포지션을 모두 확보했습니다.'}</p></div></div></section>${V.pledge(game)}<div class="evaluation-note">${o.planMessage}</div><p class="footnote">기본 평가: 보강 40% + 첫해 계획 이행 25% + 미래 가치·성장 35%. 단장 인터뷰의 약속 이행에 최대 ±4점을 별도로 반영합니다. 팬심 점수 자체를 합산하지 않습니다. 보강 1·2·3순위 확보에 50·30·20점. 육성형 선수는 퓨처스의 기술 발전을, 1군 경쟁 후보는 성장과 실제 기회 확보를 함께 봅니다. 미래 가치는 게임 내부의 성장 여력과 관찰된 발전을 사용합니다.</p><div class="result-actions"><button class="primary" data-action="download">결과 카드 저장 ↓</button><button class="ghost" data-action="season">1년차 기록 다시 보기</button><button class="ghost" data-action="reset">새 드래프트 시작</button></div>${renderMyPicks()}${renderLog()}`;}
  function showModal(kind,data={}) {
    lastFocus=document.activeElement;modal={kind,...data};
    let title='',body='';
    if(kind==='confirm') {const p=C.playerById[data.id],slot=game.schedule[game.cursor];title='지명을 확정하시겠습니까?';body=`${tag(labelRound(slot),'green')}<h3>${p.name}</h3><p>${p.school} · ${C.ROLES[p.role]} · ${p.throwHand}투${p.batHand}타</p><div class="modal-note"><p>${C.fitLabel(p,team())} · ${C.outlook(p)}<br>지명 후에는 취소할 수 없습니다. 다른 구단의 다음 지명은 자동으로 진행됩니다.</p></div><div class="modal-actions"><button class="ghost" data-action="close-modal">돌아가기</button><button class="primary" data-action="confirm-pick" data-id="${p.id}">지명 확정</button></div>`;}
    if(kind==='interview'){const p=C.playerById[data.selection.playerId];title=data.selection.round===0?'지역 1차 지명 · 현장 인터뷰':'1라운드 지명 · 현장 인터뷰';body=`<span class="eyebrow muted">WELCOME TO ${team().short}</span><h3>${C.ko.p(p.name,'이/가')} ${team().short} 유니폼을 입었습니다.</h3><p class="tiny muted">${p.school} · ${C.ROLES[p.role]}</p><div class="modal-note"><span class="eyebrow">감독의 한마디</span><p>“${C.coach(p,game)}”</p></div><div class="modal-note"><span class="eyebrow">선수의 첫 소감</span><p>“${C.interview(p,data.selection,game)}”</p></div>${V.newsCard(game.news.find(n=>n.overall===data.selection.overall))}<button class="primary" data-action="close-modal">다음 지명으로 <span class="arrow">→</span></button>`;}
    if(kind==='mock'){title='지명 전 모의 드래프트 · 고정 예측';body=V.forecasts(game,true);}
    if(kind==='news'){title='드래프트 뉴스룸';body=V.newsRoom(game);}
    if(kind==='fans'){title='팬심 변화 내역';body=V.fanHistory(game);}
    if(kind==='reset'){title='새 드래프트를 시작하시겠습니까?';body='<p>현재 지명 결과와 시즌 성적은 초기화됩니다. 필요하면 구단주 평가 화면에서 결과 카드를 먼저 저장할 수 있습니다.</p><div class="modal-actions"><button class="ghost" data-action="close-modal">취소</button><button class="primary" data-action="confirm-reset">초기화하고 팀 선택</button></div>';}
    if(kind==='catalog'){title='가상 소속 명단 · 132개';body=`<p>게임 속 야구부 평판입니다. 실존 학교의 학업 수준이나 실제 야구 전력을 평가한 자료가 아닙니다. v0.3.1에는 사용자가 다시 정한 이름을 적용했습니다. 원안은 최초 요청 명칭이며, 이름을 바꾸더라도 소속 ID와 지역·평판은 유지합니다.</p><div class="catalog-list">${['high-school','hs-club','college','independent','overseas-college'].map(kind=>`<details><summary>${{'high-school':'고교','hs-club':'고교 연령 클럽','college':'국내 대학','independent':'독립구단','overseas-college':'해외 대학'}[kind]} · ${C.catalog.filter(s=>s.kind===kind).length}개</summary><ul>${C.catalog.filter(s=>s.kind===kind).map(s=>`<li><strong>${s.name}</strong><span>${s.region||s.country} · ${s.tier||'미분류'}${s.kind==='overseas-college'&&s.weight===2?' · 낮은 등장 확률':''}</span>${s.name!==s.original?`<small>원안: ${s.original}</small>`:''}</li>`).join('')}</ul></details>`).join('')}</div><p class="context-note">공개 학교정보와 웹 자료에서 확인한 명칭 충돌을 수정했습니다. 폐교·과거 명칭·해외 표기까지 전수 검증한 것은 아니며 검색 미확인은 부재를 보장하지 않습니다.</p><button class="primary" data-action="close-modal">확인</button>`;}
    if(kind==='rules'){title='DRAFT ROOM · 플레이 가이드';body=`<p>선수 기록과 스카우팅 리포트를 읽고 우리 팀에 맞는 자원을 선택하는, 약 8분짜리 드래프트 시뮬레이션입니다.</p><ol class="modal-rule"><li>구단·난이도·지역 1차 지명을 설정합니다. 기본은 노말 / 지역 1차 OFF입니다. 난이도는 조언의 상세함과 AI의 판단 방식만 바꾸며 선수 능력·성장 확률은 바꾸지 않습니다.</li><li>시작 전 두 가상 매체의 모의 드래프트를 확인합니다. 지역 1차 ON일 때 전국 1라운드 예측은 각 매체의 지역 지명 예측을 전제로 합니다.</li><li>고정 순서로 5라운드 지명. 나머지 9개 구단은 필요 포지션·육성 성향·기존 지명을 고려해 자동 선택합니다.</li><li>지역 1차와 전국 1라운드 지명 직후 감독·선수 인터뷰, 가상 기사와 커뮤니티 반응을 확인합니다. 뉴스룸에서 다른 구단 반응도 볼 수 있습니다.</li><li>후보는 홈런·타율·타점·구속·ERA·이닝 등 22개 항목으로 정렬합니다. 해당하지 않는 값은 오름차순과 내림차순 모두 마지막입니다.</li><li>드래프트 종료 후 단장 인터뷰의 답변을 한 번 확정합니다. 팬심이 바뀌며 첫해 약속 이행에 최대 ±4점의 구단주 평가 보정이 적용됩니다.</li><li>드래프트 종료 후 입단 인터뷰와 1군·퓨처스 성적, 육성 리포트 확인. 1군 출전이 없는 신인도 많습니다.</li><li>보강 40% + 첫해 계획 이행 25% + 미래 가치 35%로 구단주 평가. 육성형 선수는 1군 미데뷔만으로 감점하지 않습니다.</li></ol><div class="modal-note"><p><strong>지역 1차 ON</strong><br>연고 지역의 고졸 후보를 구단별 1명씩 먼저 지명한 뒤, 전국 단위 5라운드를 진행합니다. 서울 3팀은 같은 후보군을 공유합니다. 지역 구분과 지명 순서는 게임용으로 단순화했으며, 과거 특정 연도의 제도를 정확히 재현하지 않습니다. 대졸·독립구단·해외파는 출신 고교가 해당 지역이어도 제외합니다. 고교 연령 BC는 고졸 지원자로 포함하는 자체 규칙을 사용합니다.</p></div><div class="modal-note"><p><strong>가상 데이터 안내</strong><br>실제 프로구단 이름을 사용하지만, 선수·소속의 야구부 평판·순위·전력·기록·수상 경력은 게임용 가상 설정입니다. 구단 로고는 사용하지 않았습니다. 새 게임마다 선수 200명이 새로 생성됩니다. 고졸 160명(80%)·대졸 30명·독립구단 6명·해외파 4명으로 구성한 게임용 비율이며 실제 통계 재현은 아닙니다. 재열람으로 성적을 다시 뽑을 수는 없습니다. 1군 진입 확률은 게임용 조정값이며 실제 KBO 통계를 재현한 수치는 아닙니다. 현재 기준일은 2026-09-16이며 2027년 입단을 가정합니다. 생일로 만 나이를 계산하고 이력에 졸업 예정과 졸업을 구분합니다. 이름은 출생연도 통계가 아닌 완성형 이름 검수 목록입니다. 해외 대학은 북미 중심이며 일본·대만의 합계 선택 가중치는 해외 대학 후보 내 6.25%입니다. 지명 거부·이도류·마이너리거 세부 경력·계약 협상은 아직 포함하지 않았습니다. 뉴스와 댓글은 실제 여론이 아닌 게임용 반응입니다. 팬심 점수 자체를 구단주 점수에 합산하지 않습니다. v0.4는 이전 버전과 저장 공간을 분리합니다.</p></div><button class="primary" data-action="close-modal">확인</button>`;}
    $('#modal-root').innerHTML=`<div class="overlay" data-action="overlay-close"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-head"><h2 id="modal-title">${title}</h2><button class="modal-close" data-action="close-modal" aria-label="닫기">×</button></div><div class="modal-body">${body}</div></section></div>`;
    $('#main').inert=true;$('#page-header').inert=true;$('#page-footer').inert=true;
    $('.modal button')?.focus();
  }
  function closeModal(){modal=null;$('#modal-root').innerHTML='';$('#main').inert=false;$('#page-header').inert=false;$('#page-footer').inert=false;if(lastFocus?.isConnected)lastFocus.focus();}
  function resetFilters(){roleFilter='ALL';pathwayFilter='ALL';tierFilter='ALL';query='';sort='rank';sortDir='asc';onlyStars=false;}
  function scrollTop(){try{window.scrollTo({top:0,behavior:'smooth'});}catch(e){}}
  function downloadResult(){
    const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=650+game.season.length*230;const x=canvas.getContext('2d');
    if(!x){notify('이 브라우저에서는 결과 이미지 저장을 지원하지 않습니다.');return;}
    const t=team(),o=game.owner;
    x.fillStyle='#f3f5f7';x.fillRect(0,0,1080,canvas.height);x.fillStyle='#14263f';x.fillRect(0,0,1080,350);
    function text(s,left,top,size,color='#17263a',weight=700){x.fillStyle=color;x.font=`${weight} ${size}px sans-serif`;x.fillText(s,left,top,960);}
    text('DRAFT ROOM / KBO EDITION',60,69,24,'#d7f564');text(t.name+' 드래프트',60,143,48,'#ffffff');text(`${C.rules.DIFFICULTIES[game.difficulty].name} · ${game.local?'지역 1차 ON':'지역 1차 OFF'} · 팬심 ${C.fanState(game).score}/100`,60,189,22,'#bac9db',500);
    text('구단주 평가',60,267,23,'#bac9db');text(`${o.grade}  /  ${o.score}점`,60,321,44,'#d7f564');
    let y=390;
    game.season.forEach(s=>{const p=C.playerById[s.playerId],v=s.stats,f=s.futures;x.fillStyle='#ffffff';x.fillRect(50,y,980,210);text(s.label+'  '+p.name+'  |  '+C.ROLES[p.role]+' · '+s.routeLabel,76,y+38,28);text(p.school+' · '+p.pathway,76,y+68,19,'#697586',500);const line=!v.games?'1군 미데뷔 · 퓨처스에서 첫해를 보냈습니다.':v.kind==='pitcher'?`1군 ${v.games}경기 · ${C.innings(v.outs)}이닝 · ERA ${v.era.toFixed(2)}`:`1군 ${v.games}경기 · AVG ${avg(v.avg)} · OPS ${v.ops.toFixed(3)}`;text(line,76,y+106,24);const farm=f.kind==='pitcher'?`퓨처스 ${f.games}경기 · ${C.innings(f.outs)}이닝 · ERA ${f.era.toFixed(2)}`:`퓨처스 ${f.games}경기 · AVG ${avg(f.avg)} · ${f.hr}홈런`;text(farm,76,y+140,22,'#667b54');text('↗ '+s.growthLabel+'  /  계획 이행 '+s.planScore+'점',76,y+180,21,'#52763c');y+=230;});
    text(`보강 ${o.needScore} / 계획 이행 ${o.production} / 미래 ${o.future} / 약속 ${o.pledge.bonus>0?'+':''}${o.pledge.bonus}`,60,y+35,26);text('가상 선수·전력·기록을 사용한 비공식 팬메이드 프로토타입',60,canvas.height-72,19,'#697586',500);text('DRAFT ROOM v0.4 · 실제 KBO 성적 예측이 아닙니다.',60,canvas.height-38,17,'#697586',500);
    try{const a=document.createElement('a');a.download=`draft-room-v04-${t.id}-${o.grade}.png`;a.href=canvas.toDataURL('image/png');document.body.appendChild(a);a.click();a.remove();notify('결과 이미지 다운로드를 요청했습니다.');}catch(e){notify('다운로드가 제한되면 별도 HTML 파일을 브라우저에서 열면 저장할 수 있습니다.');}
  }
  document.addEventListener('click',e=>{
    const btn=e.target.closest('[data-action]');if(!btn||btn.disabled)return;
    const action=btn.dataset.action,id=btn.dataset.id;
    try {
      if(action==='team'){selectedTeam=id;render();}
      if(action==='difficulty'&&!game){difficulty=id;render();document.querySelector(`[data-action="difficulty"][data-id="${id}"]`)?.focus();}
      if(action==='start'){stars.clear();game=C.createGame(selectedTeam,local,Date.now()+'-'+Math.random(),difficulty);resetFilters();selectedPlayer=null;render();scrollTop();}
      if(action==='begin-draft'){C.beginDraft(game);C.advanceToUser(game);render();refreshRows();scrollTop();}
      if(action==='mock-archive')showModal('mock');
      if(action==='news-room')showModal('news');
      if(action==='fan-history')showModal('fans');
      if(action==='gm-choice'){C.chooseGM(game,id);render();document.querySelector('.gm-section')?.scrollIntoView({behavior:'smooth',block:'start'});}
      if(action==='sort-direction'){sortDir=sortDir==='asc'?'desc':'asc';btn.textContent=sortDir==='asc'?'↑ 오름차순':'↓ 내림차순';refreshRows();}
      if(action==='player'){selectedPlayer=id;refreshRows();$('#profile').innerHTML=renderProfile();if(window.innerWidth<=700)$('#profile').scrollIntoView({behavior:'smooth',block:'start'});}
      if(action==='role'){roleFilter=id;render();refreshRows();}
      if(action==='only-stars'){onlyStars=!onlyStars;render();refreshRows();}
      if(action==='clear-filters'){resetFilters();render();refreshRows();}
      if(action==='star'){stars.has(id)?stars.delete(id):stars.add(id);refreshRows();$('#profile').innerHTML=renderProfile();save();}
      if(action==='pick'&&game?.phase==='draft'){showModal('confirm',{id});}
      if(action==='confirm-pick'&&modal?.kind==='confirm'&&game?.phase==='draft'){
        closeModal();const selection=C.addPick(game,id),name=C.playerById[id].name;C.advanceToUser(game);selectedPlayer=null;const previousSort=sort,previousDir=sortDir;resetFilters();sort=previousSort;sortDir=previousDir;render();refreshRows();scrollTop();
        if(selection.round<=1)showModal('interview',{selection});else notify(name+' 선수를 지명했습니다.');
      }
      if(action==='simulate'){C.runSeason(game);render();scrollTop();}
      if(action==='owner'){game.phase='owner';render();scrollTop();}
      if(action==='season'){game.phase='season';render();scrollTop();}
      if(action==='interviews'){game.phase='interviews';render();scrollTop();}
      if(action==='rules')showModal('rules');
      if(action==='catalog')showModal('catalog');
      if(action==='reset')showModal('reset');
      if(action==='confirm-reset'){closeModal();game=null;selectedPlayer=null;stars.clear();resetFilters();render();scrollTop();}
      if(action==='close-modal')closeModal();
      if(action==='overlay-close'&&e.target===btn)closeModal();
      if(action==='download')downloadResult();
    }catch(err){console.error(err);notify('진행 중 문제가 생겼습니다. 현재 화면에서 다시 시도할 수 있습니다.');}
  });
  document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;refreshRows();}});
  document.addEventListener('change',e=>{if(e.target.id==='local-toggle'){local=e.target.checked;render();$('#local-toggle')?.focus();}if(e.target.id==='sort'){sort=e.target.value;sortDir=C.rules.SORTS[sort].direction;document.querySelector('[data-action="sort-direction"]').textContent=sortDir==='asc'?'↑ 오름차순':'↓ 내림차순';refreshRows();}if(e.target.id==='pathway'){pathwayFilter=e.target.value;refreshRows();}if(e.target.id==='tier'){tierFilter=e.target.value;refreshRows();}});
  document.addEventListener('keydown',e=>{
    if(!modal)return;
    if(e.key==='Escape'){e.preventDefault();closeModal();}
    if(e.key==='Tab'){const els=[...document.querySelectorAll('.modal button,.modal input,.modal select,.modal summary,.modal [tabindex="0"]')].filter(x=>!x.disabled);const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}
  });
  render();refreshRows();
})();
