/* V0.6 public scouting and development UI. No hidden tool values are rendered. */
(function(root){'use strict';const C=root.DraftCore,W=root.DraftView05;
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function clubPanel(t){return `<section class="scouting-club"><h3>스카우트 팀장 · ${e(t.staff.label)}</h3><p>보조 성향: ${e(t.staff.preference)} 선호 · 추천에만 반영</p><ul>${t.detailedNeeds.map(n=>`<li><b>${e(n.label)}</b><span>${e(n.reason)}</span><small>관찰 목표 ${e(C.grades.LABELS[n.key]||{ready:'현재 기량',scoutCeiling:'미래 가치',floorGrade:'플로어'}[n.key])} ${n.target}</small></li>`).join('')}</ul><p class="context-note">세부 수요는 매 게임 달라집니다. 지명 제한이 아닌 우선 관찰 목표이며, 보강 평가에도 반영합니다.</p></section>`;}
function briefing(g,archive=false){const t=C.teamFor(g),report=g.scoutReport;return `<section class="records-head"><span class="eyebrow muted">SCOUTING DIRECTOR / BEFORE THE PICK</span><h1>세 가지 선택,<br>우리 팀의 관점.</h1><p>${e(t.short)} · ${report.scope} 추천 · ${e(report.staff.label)} / ${e(report.staff.preference)} 선호</p><p class="notice">추천은 지명 전 공개 관측값만 사용하며 이 시점에 고정됩니다. CPU가 먼저 지명할 수 있습니다. 팀장의 성향은 선수의 실제 성장률을 바꾸지 않습니다.</p></section>${clubPanel(t)}<div class="scout-recommendations">${report.candidates.map((c,i)=>{const p=C.getPlayer(g,c.playerId),gone=g.picks.some(s=>s.playerId===p.id);return `<article class="panel recommendation"><span class="eyebrow muted">${i===0?'PRIMARY PICK':'ALTERNATIVE 0'+i} · ${c.angle}</span><h2>${e(p.name)} <small>${e(C.ROLES[p.role])}</small></h2><p>${e(p.school)} · ${e(p.pathway)} · 공개 ${p.rank}위 ${gone?'· 지명 완료':''}</p><div class="recommend-grades"><span>현재 <b>${p.ready}</b></span><span>미래 가치 <b>${p.scoutCeiling}</b></span><span>실링 <b>${p.ceilingGrade}</b></span></div><p class="tag green">${p.pickTags.join(' + ')}</p><ul>${c.lines.slice(0,g.difficulty==='hard'?2:3).map(l=>`<li>${e(l)}</li>`).join('')}</ul><p class="recommend-risk"><b>우려</b> ${e(p.weakness)}</p></article>`;}).join('')}</div>${archive?'':`<div class="section-action"><button class="primary" data-action="begin-draft">추천을 참고해 드래프트 시작 →</button><p>다른 선수를 선택해도 추천 불복종 감점은 없습니다.</p></div>`}`;}
function toolSnapshot(p,tools,title){return `<section class="tool-snapshot"><h4>${e(title)} · 20–80</h4><div>${C.grades.keys(p.role).map(k=>`<span>${C.grades.LABELS[k]}<b>${tools?.[k]??'—'}</b></span>`).join('')}</div></section>`;}
function development(g,year){const original=new Set(g.picks.filter(s=>s.teamId===g.teamId).map(s=>s.playerId)),records=year.records.filter(r=>original.has(r.playerId));return `<section class="panel records-panel"><div class="section-head"><h2>보직과 성장 리포트</h2><span class="tag">시작 → 종료 평가</span></div><p class="context-note">콜업은 시즌 시작 상태로 판단합니다. 종료 평가는 그해 성장 이후의 관측치입니다. 출전하지 않아도 발전할 수 있으며, 표시 등급이 같아도 작은 변화는 누적됩니다.</p><div class="development-grid">${records.map(r=>{const p=C.getPlayer(g,r.playerId);return `<article><button class="player-link" data-action="career-player" data-id="${p.id}">${e(p.name)}</button><span class="tag ${r.route==='regular'?'green':''}">${e(r.routeLabel)}</span><p class="grade-transition">${r.startGrade??r.scoutReady} <span>→</span> ${r.scoutReady}<small>지명 당시 미래 가치 ${p.scoutCeiling}</small></p><p>${e(r.note)}</p><small>${e(r.growthLabel)} · 계획 이행 ${r.planScore}점</small></article>`;}).join('')}</div></section>`;}
W.guide=()=>`<p><strong>V0.6 · READ THE PLAYER</strong> — 관찰한 장점이 성장과 기록으로 이어지는 드래프트.</p><ol class="modal-rule"><li>구단·난이도·지역 1차 설정 → 언론 예상 → 스카우트 팀장 추천 → 지명 순서입니다.</li><li>전국 7라운드. 지역 OFF는 70명, ON은 지역 1명씩 추가해 80명을 지명합니다. 국내 대학 졸업예정자를 구단마다 최소 1명 지명해야 하며 대학 얼리는 제외됩니다.</li><li>후보 200명: 고졸 136, 국내 대졸 30, 얼리 16, 국내 독립 6, 해외 대학 4, 마이너·MLB 경험 복귀 6, 해외 독립 복귀 2. 드물게 마이너 복귀 한 자리를 짧은 MLB 경력 선수로 대체합니다.</li><li>공개 능력치는 20–80, 5단위입니다. 개별 툴의 50은 게임 내 1군 평균 수준이며 80은 예외적인 재능입니다. 종합 기량은 포지션별 툴 가중 평가이며 신인 평균 50을 뜻하지 않습니다.</li><li>현재 기량은 지금의 관측값, 미래 가치(FV)는 육성 후 예상 역할입니다. 플로어/실링은 낮은 쪽/잘 풀렸을 때의 전망이며 확정 하한·상한이 아닙니다. 즉전감·플로어·실링 태그는 중복 가능합니다.</li><li>툴은 서로 다르게 성장합니다. 투수의 구위·커맨드·변화구는 투구 성적, 체력은 소화 이닝에 연결됩니다. 야수의 컨택·장타력·주력·수비는 타격과 역할에 반영되며 선구안은 보조 항목입니다.</li><li>2027–2031년 5시즌. 전년도 보직은 다음 해 유지 판단에 반영하고 출전량은 연차에 따라 확대합니다. 건강 문제·부진·보직 경쟁에 따라 역할이 줄 수 있으며 이유를 표시합니다.</li><li>선발 승수는 5이닝 이상 투구, 실점, 득점 지원, 불펜을 반영합니다. 좋은 선발의 두 자릿수 승수와 거포의 20홈런 이상이 가능합니다. 보장 성적이 아닙니다.</li><li>전체 구단 기록실에서 CPU 선수, 연도별 1군·퓨처스·누적 기록을 확인합니다. 개인상은 동기 내 수상이며 팀 전력과 포스트시즌은 간소화 모델입니다.</li><li>자동 1대1 트레이드는 2~4년 차 종료 후 가능합니다. 방출은 3~4년 차 종료 후 만 23세 이상, 2년 연속 1군 기록 없음, 공개 기량 40 미만일 때 검토합니다. 방출 후 재계약은 없습니다.</li><li>이지에서만 선수의 선호 구단을 공개합니다. 노말·하드에서 비공개이며 V0.6에서는 계약이나 성장에 영향을 주지 않습니다. 계약 협상·지명 거부는 포함하지 않습니다.</li><li>진행 JSON 저장·복원이 가능합니다. V0.5와 모델이 달라 호환되지 않으며 기존 V0.5 파일과 저장을 덮어쓰지 않습니다.</li></ol><p class="notice">해외 복귀는 국내 프로 미입단자의 첫 국내 도전이라는 가상 지원 규칙입니다. 실제 연도별 복귀 유예·계약·드래프트 자격을 재현하지 않습니다. 해외 기록은 리그 수준과 표본이 달라 국내 기록과 직접 비교할 수 없습니다. 구단명 외 선수·소속·기록·전력·기사 등은 가상 데이터입니다.</p>`;
root.DraftView06={clubPanel,briefing,toolSnapshot,development};
})(typeof window!=='undefined'?window:globalThis);
