/* Pure HTML presenters for the v0.4 newsroom and draft strategy. */
(function(root){
'use strict';
const C=root.DraftCore;
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const signed=n=>(n>0?'+':'')+n;
function sortOptions(selected){return [...new Set(Object.values(C.rules.SORTS).map(s=>s.group))].map(group=>`<optgroup label="${group}">${Object.entries(C.rules.SORTS).filter(([,s])=>s.group===group).map(([id,s])=>`<option value="${id}" ${selected===id?'selected':''}>${s.label}</option>`).join('')}</optgroup>`).join('');}
function sortedStat(p,key,team){const s=C.rules.SORTS[key],n=C.rules.sortValue(p,key,team);return {value:n==null?'—':key==='outs'?C.innings(n):key==='era'?n.toFixed(2):['avg','ops'].includes(key)?n.toFixed(3):key==='velocity'?n+' km/h':String(n),label:s.label};}
function scoutTools(p){const pitcher=p.record.kind==='pitcher',tools=[['준비도',p.ready],['성장 기대',p.scoutCeiling],...(pitcher?[['제구',p.control]]:[['장타력',p.power],['주력',p.speed],['수비',p.defense]])];return `<section class="tool-estimates"><span class="mini-heading">공개 스카우트 추정치 · 100점 척도</span><div>${tools.map(([label,n])=>`<span><b>${n}</b>${label}</span>`).join('')}</div><p>실제 준비도·성장 한계를 확정하는 수치가 아닙니다. 모든 난이도에서 같은 공개 평가를 사용합니다.</p></section>`;}
function forecasts(g,archive=false){return `<section class="mock-section"><span class="eyebrow muted">PRE-DRAFT / MEDIA ROOM</span><h1>${archive?'지명 전, 언론은 어떻게 예상했을까요?':'언론의 예상은, 선택의 시작일 뿐.'}</h1><p class="mock-intro">두 가상 매체가 같은 공개 자료를 서로 다르게 해석했습니다. 예측은 이 게임이 시작되기 전에 고정되며 실제 지명과 다를 수 있습니다.</p><p class="notice">${g.local?'지역 1차 ON · 전국 1라운드 예상은 각 매체가 먼저 예측한 지역 1차 결과를 전제로 합니다. 실제 지역 지명이 달라도 예측을 다시 쓰지 않습니다.':'지역 1차 OFF · 전국 1라운드 10개 구단의 지명을 예측합니다.'} 숨은 능력과 미래 성적은 사용하지 않습니다.</p><div class="mock-grid">${g.forecasts.map(f=>`<article class="panel mock-outlet"><div class="outlet-heading"><span class="eyebrow">${f.id==='diamond'?'THE DIAMOND DAILY':'FUTURE BASEBALL'}</span><h2>${f.name}</h2><p>${f.style}</p></div>${[1,...(g.local?[0]:[])].map(round=>`<details class="mock-round" ${round===1?'open':''}><summary>${round===0?'지역 1차 예상 · 보조 시나리오':'전국 1라운드 예상'} <span>10 PICKS</span></summary><ol class="mock-list">${f.picks.filter(s=>s.round===round).map((s,i)=>{const p=C.getPlayer(g,s.playerId),t=C.teamById[s.teamId],actual=g.picks.find(x=>x.round===round&&x.teamId===s.teamId);return `<li data-player-id="${p.id}"><span class="mock-order">${String(i+1).padStart(2,'0')}</span><div><span class="mock-team">${t.short}</span><strong>${p.name} <small>${C.ROLES[p.role]}</small></strong><span class="mock-school">${p.school}</span><p>${s.reason}</p>${actual?`<span class="forecast-result ${actual.playerId===p.id?'correct':''}">${actual.playerId===p.id?'예측 일치':'실제 지명: '+C.getPlayer(g,actual.playerId).name}</span>`:''}</div></li>`;}).join('')}</ol></details>`).join('')}</article>`).join('')}</div>${archive?'':`<div class="section-action"><button class="primary" data-action="begin-draft">예상을 확인했습니다 · 드래프트 시작 →</button><p>${C.rules.DIFFICULTIES[g.difficulty].name} · 예측은 나중에도 다시 볼 수 있습니다.</p></div>`}</section>`;}
function newsCard(n){return `<article class="news-article" data-news-id="${n.id}"><span class="eyebrow muted">DRAFT ROOM NEWS · ${n.label}</span><h3>${n.headline}</h3><p class="news-body">${n.body}</p><p class="fiction-label">게임 속 가상 기사와 커뮤니티 반응입니다.</p><div class="community"><h4>커뮤니티의 세 가지 시선</h4>${n.comments.map(c=>`<div class="comment"><span><b>${c.handle}</b><em>${c.tone}</em></span><p>${c.text}</p></div>`).join('')}</div></article>`;}
function newsRoom(g){return `<p>지역 1차와 전국 1라운드 지명 직후의 반응입니다. 이후 지명이나 시즌 결과에 맞춰 과거 기사를 바꾸지 않습니다.</p>${g.news.length?[...g.news].reverse().map(newsCard).join(''):'<div class="empty">아직 주요 지명이 없습니다. 지명 후 기사가 쌓입니다.</div>'}`;}
function infoBar(g){const fan=C.fanState(g);return `<aside class="game-info-bar"><div><span class="difficulty-badge">${C.rules.DIFFICULTIES[g.difficulty].name}</span><button class="fan-pill" data-action="fan-history" aria-label="팬심 변화 내역 보기">팬심 <b>${fan.score}</b><small>/100 · ${fan.label}</small></button></div><div><button class="ghost" data-action="mock-archive">언론 예상</button><button class="ghost" data-action="news-room">뉴스룸 <span>${g.news.length}</span></button></div></aside>`;}
function gm(g){const opts=C.gmOptions(g),selected=opts.find(c=>c.id===g.gmChoice);return `<section class="panel gm-section"><span class="eyebrow muted">GM PRESS CONFERENCE</span><h2>단장님, 어떤 첫해를 약속하시겠습니까?</h2><p class="gm-question">기자: “이번 지명에 담긴 방향과 팬들이 지켜봐야 할 기준을 말씀해 주십시오.”</p>${selected?`<div class="gm-answered"><span class="tag green">답변 확정</span><h3>${selected.title}</h3><blockquote>“${selected.answer}”</blockquote><p><strong>약속:</strong> ${selected.promise}</p><p>${selected.reaction}</p><span class="fan-change">인터뷰 당시 팬심 ${signed(selected.delta)}</span><p class="tiny muted">확정한 답변은 바꿀 수 없습니다. 시즌 뒤 약속의 이행 여부를 돌아봅니다.</p></div>`:`<p class="context-note">답변을 고르면 즉시 확정됩니다. 선수 능력이나 출전 확률은 바뀌지 않으며 팬심과 시즌 후 약속 평가에 반영됩니다.</p><div class="gm-options">${opts.map(c=>`<article><h3>${c.title}</h3><blockquote>“${c.answer}”</blockquote><p><b>평가 기준</b><br>${c.promise}</p><p>${c.reaction}</p><p class="tiny muted">${c.risk}</p><button class="primary" data-action="gm-choice" data-id="${c.id}">이 답변으로 인터뷰 · 팬심 ${signed(c.delta)}</button></article>`).join('')}</div>`}</section>`;}
function fanHistory(g){const f=C.fanState(g);return `<div class="fan-overview"><strong>${f.score}<small>/100</small></strong><p>${f.label} · 가상 팬심 지수이며 실제 여론 조사 비율이 아닙니다.</p></div><ol class="fan-timeline">${f.timeline.map(x=>`<li><div><b>${e(x.label)}</b><span>${signed(x.delta)}</span></div><meter min="0" max="100" value="${x.score}">${x.score}</meter><small>${x.score}/100</small></li>`).join('')}</ol><p class="context-note">같은 기사를 재열람하거나 새로고침해도 중복 적용하지 않습니다. 팬심 점수 자체를 구단주 점수에 더하지 않습니다.</p>`;}
function pledge(g){const o=g.owner,c=C.press.GM_CHOICES.find(x=>x.id===g.gmChoice);return `<section class="panel pledge-review"><span class="eyebrow muted">ACCOUNTABILITY / 약속 평가</span><h2>${o.pledge.status} <span>${signed(o.pledge.bonus)}점</span></h2><p>“${c.answer}”</p><p><b>${o.pledge.detail}</b></p><p>기존 평가 ${o.baseScore}점 + 약속 보정 ${signed(o.pledge.bonus)}점 = 최종 ${o.score}점입니다. 보강·계획 이행·미래 가치의 40·25·35 비중은 유지하며, 약속 보정은 최대 ±4점입니다.</p></section>`;}
root.DraftView04={sortOptions,sortedStat,scoutTools,forecasts,newsCard,newsRoom,infoBar,gm,fanHistory,pledge};
})(typeof window!=='undefined'?window:globalThis);
